import { NextResponse } from 'next/server'
import { createSupabaseServiceClient } from '@/lib/supabase/server'
import { requireManager } from '@/lib/route-auth'

const VOCABULARIO: string[] = [
  // ── Limpeza e higiene ──────────────────────────────────────────
  'LIMPEZA', 'LIMPEZAS', 'LIMPAR', 'LIMPANDO', 'LIMPEI', 'LIMPO', 'LIMPA',
  'VARREDURA', 'VARRER', 'VARRENDO', 'VARRI', 'VARRIDO',
  'VASSOURA', 'VASSOURAS', 'VASSOURAR',
  'HIGIENIZAÇÃO', 'HIGIENIZAR', 'HIGIENIZANDO', 'HIGIENIZEI', 'HIGIENIZADO',
  'DESINFECÇÃO', 'DESINFETAR', 'DESINFETANDO', 'DESINFETEI', 'DESINFETADO',
  'DESINFESTAÇÃO', 'DESINFESTANDO', 'DESINFESTEI',
  'ESTERILIZAÇÃO', 'ESTERILIZAR', 'ESTERILIZANDO', 'ESTERILIZEI',
  'LAVAGEM', 'LAVAR', 'LAVANDO', 'LAVEI', 'LAVADO',
  'ENXÁGUE', 'ENXAGUAR', 'ENXAGUANDO', 'ENXAGUEI',
  'FAXINA', 'FAXINANDO', 'FAXINAR', 'FAXINEI',
  'DESCARTE', 'DESCARTANDO', 'DESCARTAR', 'DESCARTEI', 'DESCARTADO',
  'RESÍDUO', 'RESÍDUOS', 'LIXO', 'LIXEIRA', 'LIXEIRAS',
  'DEDETIZAÇÃO', 'DESRATIZAÇÃO', 'SANITIZAÇÃO',
  'ESFREGÃO', 'PANO', 'PANOS', 'RODO', 'BALDE', 'BALDES',
  'DETERGENTE', 'DETERGENTES', 'DESINFETANTE', 'DESINFETANTES',
  'ÁLCOOL', 'HIPOCLORITO', 'CLORO',

  // ── Organização e ordenação ────────────────────────────────────
  'ORGANIZAÇÃO', 'ORGANIZAR', 'ORGANIZANDO', 'ORGANIZEI', 'ORGANIZADO',
  'ARRUMAÇÃO', 'ARRUMAR', 'ARRUMANDO', 'ARRUMEI', 'ARRUMADO',
  'ORDENAÇÃO', 'ORDENAR', 'ORDENANDO', 'ORDENEI', 'ORDENADO',
  'SEPARAÇÃO', 'SEPARAR', 'SEPARANDO', 'SEPAREI', 'SEPARADO',
  'SELEÇÃO', 'SELECIONAR', 'SELECIONANDO', 'SELECIONEI', 'SELECIONADO',
  'TRIAGEM', 'TRIAR', 'TRIANDO', 'TRIEI',
  'MONTAGEM', 'MONTAR', 'MONTANDO', 'MONTEI', 'MONTADO',
  'DESMONTAGEM', 'DESMONTAR', 'DESMONTANDO', 'DESMONTEI',
  'EMPILHAMENTO', 'EMPILHAR', 'EMPILHANDO', 'EMPILHEI',
  'ARMAZENAMENTO', 'ARMAZENAR', 'ARMAZENANDO', 'ARMAZENEI', 'ARMAZENADO',
  'DISPOSIÇÃO', 'DISPOR', 'DISPONDO', 'DISPUS',
  'ALOCAÇÃO', 'ALOCAR', 'ALOCANDO', 'ALOQUEI',
  'ACONDICIONAMENTO', 'ACONDICIONAR', 'ACONDICIONANDO',
  'EMPACOTAMENTO', 'EMPACOTAR', 'EMPACOTANDO', 'EMPACOTEI',

  // ── Atendimento e recepção ─────────────────────────────────────
  'RECEPÇÃO', 'RECEPCIONAR', 'RECEPCIONANDO', 'RECEPCIONEI', 'RECEPCIONADO',
  'ATENDIMENTO', 'ATENDER', 'ATENDENDO', 'ATENDI', 'ATENDIDO',
  'ACOLHIMENTO', 'ACOLHER', 'ACOLHENDO', 'ACOLHI',
  'ORIENTAÇÃO', 'ORIENTAR', 'ORIENTANDO', 'ORIENTEI', 'ORIENTADO',
  'ENCAMINHAMENTO', 'ENCAMINHAR', 'ENCAMINHANDO', 'ENCAMINHEI',
  'SUPORTE', 'APOIO', 'APOIOS',
  'AGENDAMENTO', 'AGENDAR', 'AGENDANDO', 'AGENDEI', 'AGENDADO',
  'VISITA', 'VISITAS', 'VISITAR', 'VISITANDO', 'VISITEI',
  'RECLAMAÇÃO', 'RECLAMAR', 'RECLAMANDO', 'RECLAMEI',
  'DEMANDA', 'DEMANDAS', 'DEMANDAR',
  'USUÁRIO', 'USUÁRIOS', 'CLIENTE', 'CLIENTES',
  'PÚBLICO', 'PROFESSOR', 'PROFESSORES', 'ALUNO', 'ALUNOS',
  'SERVIDOR', 'SERVIDORES', 'FUNCIONÁRIO', 'FUNCIONÁRIOS',
  'VISITANTE', 'VISITANTES', 'PARCEIRO', 'PARCEIROS',

  // ── Documentação e arquivo ─────────────────────────────────────
  'DOCUMENTO', 'DOCUMENTOS', 'DOCUMENTAÇÃO', 'DOCUMENTAR', 'DOCUMENTANDO', 'DOCUMENTADO',
  'ARQUIVAMENTO', 'ARQUIVAR', 'ARQUIVANDO', 'ARQUIVEI', 'ARQUIVADO',
  'ARQUIVO', 'ARQUIVOS', 'PASTA', 'PASTAS',
  'DIGITAÇÃO', 'DIGITAR', 'DIGITANDO', 'DIGITEI', 'DIGITADO',
  'IMPRESSÃO', 'IMPRIMIR', 'IMPRIMINDO', 'IMPRIMI', 'IMPRESSO',
  'CATALOGAÇÃO', 'CATALOGAR', 'CATALOGANDO', 'CATALOGUEI', 'CATALOGADO',
  'PROTOCOLO', 'PROTOCOLANDO', 'PROTOCOLAR', 'PROTOCOLEI', 'PROTOCOLADO',
  'PLANILHA', 'PLANILHAS', 'PLANILHAR', 'PLANILHANDO',
  'RELATÓRIO', 'RELATÓRIOS', 'RELATAR', 'RELATANDO', 'RELATEI',
  'FORMULÁRIO', 'FORMULÁRIOS', 'FORMULAR',
  'FICHA', 'FICHAS', 'FICHÁRIO', 'FICHÁRIOS',
  'CADASTRO', 'CADASTROS', 'CADASTRAR', 'CADASTRANDO', 'CADASTREI', 'CADASTRADO',
  'CADASTRAMENTO',
  'PREENCHIMENTO', 'PREENCHER', 'PREENCHENDO', 'PREENCHEI', 'PREENCHIDO',
  'VERIFICAÇÃO', 'VERIFICAR', 'VERIFICANDO', 'VERIFIQUEI', 'VERIFICADO',
  'CONFERÊNCIA', 'CONFERIR', 'CONFERINDO', 'CONFERI', 'CONFERIDO',
  'CLASSIFICAÇÃO', 'CLASSIFICAR', 'CLASSIFICANDO', 'CLASSIFIQUEI', 'CLASSIFICADO',
  'RECEBIMENTO', 'RECEBER', 'RECEBENDO', 'RECEBI', 'RECEBIDO',
  'ENTREGA', 'ENTREGAR', 'ENTREGANDO', 'ENTREGEI', 'ENTREGUE',
  'ENVIO', 'ENVIAR', 'ENVIANDO', 'ENVIEI', 'ENVIADO',
  'EMISSÃO', 'EMITIR', 'EMITINDO', 'EMITI', 'EMITIDO',
  'CONTROLE', 'CONTROLAR', 'CONTROLANDO', 'CONTROLEI', 'CONTROLADO',
  'REGISTRO', 'REGISTROS', 'REGISTRAR', 'REGISTRANDO', 'REGISTREI', 'REGISTRADO',
  'ASSINATURA', 'ASSINAR', 'ASSINANDO', 'ASSINEI', 'ASSINADO',
  'CÓPIA', 'CÓPIAS', 'COPIAR', 'COPIANDO', 'COPIEI', 'COPIADO',
  'XEROX', 'XEROCAR', 'XEROCANDO', 'XEROQUEI',
  'DIGITALIZAÇÃO', 'DIGITALIZAR', 'DIGITALIZANDO', 'DIGITALIZEI', 'DIGITALIZADO',
  'ESCANEAMENTO', 'ESCANEAR', 'ESCANEANDO', 'ESCANEEI', 'ESCANEADO',
  'LANÇAMENTO', 'LANÇAR', 'LANÇANDO', 'LANCEI', 'LANÇADO',
  'ANOTAÇÃO', 'ANOTAÇÕES', 'ANOTAR', 'ANOTANDO', 'ANOTEI', 'ANOTADO',
  'TRANSCRIÇÃO', 'TRANSCREVER', 'TRANSCREVENDO', 'TRANSCREVI',
  'CONTRATO', 'CONTRATOS', 'TERMO', 'TERMOS', 'DECLARAÇÃO', 'DECLARAÇÕES',
  'OFÍCIO', 'OFÍCIOS', 'MEMORANDO', 'MEMORANDOS', 'ATA', 'ATAS',
  'PORTARIA', 'PORTARIAS', 'EDITAL', 'EDITAIS', 'PROCESSO', 'PROCESSOS',
  'NORMA', 'NORMAS', 'MANUAL', 'MANUAIS', 'INSTRUÇÃO', 'INSTRUÇÕES',

  // ── Reuniões e capacitação ─────────────────────────────────────
  'REUNIÃO', 'REUNIÕES', 'REUNIR', 'REUNINDO', 'REUNI', 'REUNIDO',
  'TREINAMENTO', 'TREINAMENTOS', 'TREINAR', 'TREINANDO', 'TREINEI', 'TREINADO',
  'CAPACITAÇÃO', 'CAPACITAR', 'CAPACITANDO', 'CAPACITEI', 'CAPACITADO',
  'CURSO', 'CURSOS', 'CURSANDO', 'CURSEI',
  'PALESTRA', 'PALESTRAS', 'PALESTRAR', 'PALESTRANDO',
  'APRESENTAÇÃO', 'APRESENTAÇÕES', 'APRESENTAR', 'APRESENTANDO', 'APRESENTEI', 'APRESENTADO',
  'WORKSHOP', 'WORKSHOPS', 'SEMINÁRIO', 'SEMINÁRIOS',
  'INSTRUÇÃO', 'INSTRUIR', 'INSTRUINDO', 'INSTRUÍ', 'INSTRUÍDO',
  'DEBATE', 'DEBATES', 'DEBATER', 'DEBATENDO', 'DEBATI',
  'DISCUSSÃO', 'DISCUSSÕES', 'DISCUTIR', 'DISCUTINDO', 'DISCUTI',
  'AULA', 'AULAS', 'MINISTRAR', 'MINISTRANDO', 'MINISTREI',
  'DISCIPLINA', 'DISCIPLINAS', 'MÓDULO', 'MÓDULOS',
  'CERTIFICADO', 'CERTIFICADOS', 'CERTIFICAÇÃO',
  'EVENTO', 'EVENTOS', 'CONGRESSO', 'CONGRESSOS', 'SIMPÓSIO', 'SIMPÓSIOS',
  'CONFERÊNCIA', 'CONFERÊNCIAS',

  // ── Monitoramento e supervisão ─────────────────────────────────
  'MONITORAMENTO', 'MONITORAR', 'MONITORANDO', 'MONITOREI', 'MONITORADO',
  'ACOMPANHAMENTO', 'ACOMPANHAR', 'ACOMPANHANDO', 'ACOMPANHEI', 'ACOMPANHADO',
  'SUPERVISÃO', 'SUPERVISIONAR', 'SUPERVISIONANDO', 'SUPERVISIONEI',
  'COLABORAÇÃO', 'COLABORAR', 'COLABORANDO', 'COLABOREI', 'COLABORADO',
  'AUXILIAR', 'AUXILIANDO', 'AUXILIEI', 'AUXILIADO',
  'AJUDAR', 'AJUDANDO', 'AJUDEI', 'AJUDADO',
  'APOIAR', 'APOIANDO', 'APOIEI', 'APOIADO',
  'FISCALIZAÇÃO', 'FISCALIZAR', 'FISCALIZANDO', 'FISCALIZEI',
  'AUDITORIA', 'AUDITAR', 'AUDITANDO', 'AUDITEI',
  'AVALIAÇÃO', 'AVALIAR', 'AVALIANDO', 'AVALIEI', 'AVALIADO',
  'FEEDBACK', 'RELATORIA', 'INDICADOR', 'INDICADORES',
  'DIAGNÓSTICO', 'DIAGNOSTICAR', 'DIAGNOSTICANDO',
  'OBSERVAÇÃO', 'OBSERVAÇÕES', 'OBSERVAR', 'OBSERVANDO', 'OBSERVEI',

  // ── Estoque e suprimentos ──────────────────────────────────────
  'ESTOQUE', 'ESTOCAR', 'ESTOCANDO', 'ESTOQUEI', 'ESTOCADO',
  'MATERIAL', 'MATERIAIS',
  'SUPRIMENTO', 'SUPRIMENTOS', 'SUPRIR', 'SUPRINDO', 'SUPRI',
  'INSUMO', 'INSUMOS',
  'INVENTÁRIO', 'INVENTARIAR', 'INVENTARIANDO', 'INVENTARIEI',
  'REQUISIÇÃO', 'REQUISIÇÕES', 'REQUISITAR', 'REQUISITANDO', 'REQUISITEI',
  'COMPRAS', 'COMPRAR', 'COMPRANDO', 'COMPREI', 'COMPRADO',
  'REPOSIÇÃO', 'REPOR', 'REPONDO', 'REPUS', 'REPOSTO',
  'ETIQUETAGEM', 'ETIQUETAR', 'ETIQUETANDO', 'ETIQUETEI', 'ETIQUETADO',
  'ETIQUETA', 'ETIQUETAS',
  'CONTAGEM', 'CONTAR', 'CONTANDO', 'CONTEI', 'CONTADO',
  'PEDIDO', 'PEDIDOS', 'PEDIR', 'PEDINDO', 'PEDI',
  'FORNECIMENTO', 'FORNECEDOR', 'FORNECEDORES', 'FORNECER', 'FORNECENDO',
  'PRODUTO', 'PRODUTOS', 'ITEM', 'ITENS',
  'CONSUMÍVEL', 'CONSUMÍVEIS', 'INSUMOS',
  'RECEBIMENTO', 'NOTA', 'NOTAS', 'FATURA', 'FATURAS',
  'DEVOLUÇÃO', 'DEVOLVER', 'DEVOLVENDO', 'DEVOLVI',

  // ── Informática e tecnologia ───────────────────────────────────
  'INFORMÁTICA',
  'COMPUTADOR', 'COMPUTADORES', 'NOTEBOOK', 'NOTEBOOKS',
  'SISTEMA', 'SISTEMAS',
  'IMPRESSORA', 'IMPRESSORAS', 'SCANNER', 'SCANNERS',
  'EQUIPAMENTO', 'EQUIPAMENTOS',
  'MANUTENÇÃO', 'MANUTENÇÕES', 'MANTER', 'MANTENDO', 'MANTIVE', 'MANTIDO',
  'INSTALAÇÃO', 'INSTALAR', 'INSTALANDO', 'INSTALEI', 'INSTALADO',
  'CONFIGURAÇÃO', 'CONFIGURAR', 'CONFIGURANDO', 'CONFIGUREI', 'CONFIGURADO',
  'ATUALIZAÇÃO', 'ATUALIZAR', 'ATUALIZANDO', 'ATUALIZEI', 'ATUALIZADO',
  'ACESSO', 'ACESSAR', 'ACESSANDO', 'ACESSEI', 'ACESSADO',
  'BACKUP', 'BACKUPS',
  'REDE', 'REDES', 'INTERNET', 'SERVIDOR', 'SERVIDORES',
  'HARDWARE', 'SOFTWARE', 'APLICATIVO', 'APLICATIVOS',
  'SUPORTE', 'TÉCNICO', 'TÉCNICA',
  'CÂMERA', 'CÂMERAS', 'PROJETOR', 'PROJETORES',
  'TABLET', 'CELULAR', 'CELULARES', 'TELEFONE', 'TELEFONES',
  'EMAIL', 'E-MAIL', 'MENSAGEM', 'MENSAGENS',
  'SENHA', 'SENHAS', 'LOGIN', 'USUÁRIO', 'USUÁRIOS',

  // ── Laboratório geral ──────────────────────────────────────────
  'LABORATÓRIO', 'LABORATÓRIOS', 'LAB',
  'ANÁLISE', 'ANÁLISES', 'ANALISAR', 'ANALISANDO', 'ANALISEI', 'ANALISADO',
  'AMOSTRA', 'AMOSTRAS', 'AMOSTRAR', 'AMOSTRANDO', 'AMOSTREI',
  'EXPERIMENTO', 'EXPERIMENTOS', 'EXPERIMENTAR', 'EXPERIMENTANDO', 'EXPERIMENTEI',
  'PESQUISA', 'PESQUISAS', 'PESQUISAR', 'PESQUISANDO', 'PESQUISEI', 'PESQUISADO',
  'COLETA', 'COLETAS', 'COLETAR', 'COLETANDO', 'COLETEI', 'COLETADO',
  'MEDIÇÃO', 'MEDIÇÕES', 'MEDIR', 'MEDINDO', 'MEDI', 'MEDIDO',
  'PESAGEM', 'PESAR', 'PESANDO', 'PESEI', 'PESADO',
  'CALIBRAÇÃO', 'CALIBRAR', 'CALIBRANDO', 'CALIBREI', 'CALIBRADO',
  'PREPARAÇÃO', 'PREPARAR', 'PREPARANDO', 'PREPAREI', 'PREPARADO',
  'PREPARO', 'PREPAR',
  'MISTURA', 'MISTURAS', 'MISTURAR', 'MISTURANDO', 'MISTUREI', 'MISTURADO',
  'SOLUÇÃO', 'SOLUÇÕES', 'DILUIÇÃO', 'DILUIR', 'DILUINDO', 'DILUÍ',
  'REAGENTE', 'REAGENTES', 'SUBSTÂNCIA', 'SUBSTÂNCIAS',
  'VIDRARIA', 'VIDRARIAS', 'PIPETA', 'PIPETAS', 'BURETA', 'BURETAS',
  'BÉQUER', 'BÉQUERES', 'ERLENMEYER', 'PROVETA', 'PROVETAS',
  'RESULTADO', 'RESULTADOS',
  'LAUDO', 'LAUDOS', 'LAUDO TÉCNICO',
  'EXAME', 'EXAMES',
  'INSPEÇÃO', 'INSPEÇÕES', 'INSPECIONAR', 'INSPECIONANDO', 'INSPECIONEI',
  'VISTORIA', 'VISTORIAS', 'VISTORIAR', 'VISTORIANDO', 'VISTORIEI',
  'MICROSCÓPIO', 'MICROSCÓPIOS', 'LÂMINA', 'LÂMINAS', 'LAMÍNULA',
  'CENTRÍFUGA', 'CENTRIFUGAR', 'CENTRÍFUGAS', 'CENTRÍFUGANDO',
  'AUTOCLAVE', 'AUTOCLAVAR', 'AUTOCLAVANDO',
  'BALANÇA', 'BALANÇAS', 'PESAR', 'AFERIÇÃO',
  'ESTUFA', 'ESTUFAS', 'INCUBADORA', 'INCUBADORAS',
  'AGITADOR', 'AGITAR', 'AGITANDO', 'AGITEI',
  'EXTRAÇÃO', 'EXTRAIR', 'EXTRAINDO', 'EXTRAÍ', 'EXTRAÍDO',
  'FILTRAÇÃO', 'FILTRAR', 'FILTRANDO', 'FILTREI', 'FILTRADO',
  'TITULAÇÃO', 'TITULAR', 'TITULANDO', 'TITULEI',
  'CONCENTRAÇÃO', 'CONCENTRAR', 'CONCENTRANDO', 'CONCENTREI',
  'INOCULAÇÃO', 'INOCULAR', 'INOCULANDO', 'INOCULEI',
  'CULTURA', 'CULTURAS', 'MEIO', 'MEIOS', 'CALDO', 'CALDOS',
  'PLACA', 'PLACAS', 'PETRI', 'SEMEADURA', 'SEMEAR', 'SEMEANDO',
  'REPIQUE', 'REPICAR', 'REPICANDO', ' REPIQUEI',
  'ISOLAMENTO', 'ISOLAR', 'ISOLANDO', 'ISOLEI', 'ISOLADO',
  'IDENTIFICAÇÃO', 'IDENTIFICAR', 'IDENTIFICANDO', 'IDENTIFIQUEI',
  'COLORAÇÃO', 'COLORIR', 'COLORINDO', 'COLORAÇÃO',
  'GRAM', 'COLORAÇÃO DE GRAM',
  'CROMATOGRAFIA', 'ESPECTROFOTOMETRIA', 'ESPECTROSCOPIA',
  'ABSORBÂNCIA', 'ABSORBÂNCIA', 'LEITURA',
  'PH', 'ACIDEZ', 'ALCALINIDADE', 'UMIDADE', 'TEMPERATURA',
  'CONCENTRAÇÃO', 'DIÂMETRO', 'COMPRIMENTO', 'LARGURA', 'ALTURA',
  'VOLUME', 'MASSA', 'PESO', 'DENSIDADE', 'VISCOSIDADE',

  // ── Agronomia e agricultura ────────────────────────────────────
  'AGRONOMIA', 'AGRONÔMICO', 'AGRONÔMICA',
  'SOLO', 'SOLOS', 'TERRA', 'TERRAS', 'SUBST RATO', 'SUBSTRATO', 'SUBSTRATOS',
  'PLANTA', 'PLANTAS', 'PLANTIO', 'PLANTIOS', 'PLANTAR', 'PLANTANDO', 'PLANTEI',
  'CULTURA', 'CULTURAS', 'CULTIVAR', 'CULTIVANDO', 'CULTIVEI', 'CULTIVO', 'CULTIVOS',
  'SEMEADURA', 'SEMEAR', 'SEMEANDO', 'SEMEEI',
  'SEMENTE', 'SEMENTES',
  'GERMINAÇÃO', 'GERMINAR', 'GERMINANDO', 'GERMINEI',
  'MUDA', 'MUDAS',
  'PODA', 'PODAS', 'PODAR', 'PODANDO', 'PODEI',
  'ADUBAÇÃO', 'ADUBAR', 'ADUBANDO', 'ADUBEI', 'ADUBADO',
  'ADUBO', 'ADUBOS', 'FERTILIZANTE', 'FERTILIZANTES',
  'FERTILIZAÇÃO', 'FERTILIZAR', 'FERTILIZANDO', 'FERTILIZEI',
  'IRRIGAÇÃO', 'IRRIGAR', 'IRRIGANDO', 'IRRIGANDO', 'IRRIGADO',
  'ÁGUA', 'ÁGUAS', 'MOLHAR', 'MOLHANDO', 'MOLHEI',
  'DRENAGEM', 'DRENAR', 'DRENANDO', 'DRENEI',
  'HERBICIDA', 'HERBICIDAS', 'PESTICIDA', 'PESTICIDAS',
  'DEFENSIVO', 'DEFENSIVOS', 'AGROTÓXICO', 'AGROTÓXICOS',
  'FUNGICIDA', 'FUNGICIDAS', 'INSETICIDA', 'INSETICIDAS',
  'APLICAÇÃO', 'APLICAR', 'APLICANDO', 'APLIQUEI', 'APLICADO',
  'PULVERIZAÇÃO', 'PULVERIZAR', 'PULVERIZANDO', 'PULVERIZEI',
  'CALAGEM', 'CALCÁRIO', 'CALAGEM DO SOLO',
  'CORREÇÃO', 'CORRIGIR', 'CORRIGINDO', 'CORRIGI',
  'ANÁLISE DE SOLO', 'ANALISE DE SOLO',
  'COLHEITA', 'COLHEITAS', 'COLHER', 'COLHENDO', 'COLHI', 'COLHIDO',
  'PRODUÇÃO', 'PRODUZIR', 'PRODUZINDO', 'PRODUZI', 'PRODUZIDO',
  'PRODUTIVIDADE',
  'SAFRA', 'SAFRAS',
  'CAMPO', 'CAMPOS',
  'PARCELA', 'PARCELAS',
  'TALHÃO', 'TALHÕES',
  'ESTUFA', 'ESTUFAS', 'CASA DE VEGETAÇÃO',
  'VIVEIRO', 'VIVEIROS',
  'HORTA', 'HORTAS',
  'POMAR', 'POMARES',
  'RAIZ', 'RAÍZES', 'CAULE', 'CAULES', 'FOLHA', 'FOLHAS', 'FRUTO', 'FRUTOS',
  'FLOR', 'FLORES', 'ESPIGA', 'ESPIGAS', 'GRÃO', 'GRÃOS',
  'SOJA', 'MILHO', 'FEIJÃO', 'ARROZ', 'CANA', 'ALGODÃO',
  'CAFÉ', 'EUCALIPTO', 'TOMATE', 'TRIGO', 'SORGO',
  'PASTAGEM', 'PASTO', 'FORRAGEM', 'FORRAGEIRA',
  'GADO', 'BOVINO', 'OVINO', 'SUÍNO', 'AVES',
  'FITOPATOLOGIA', 'ENTOMOLOGIA', 'FITOPATOLÓGICO',
  'PRAGA', 'PRAGAS', 'DOENÇA', 'DOENÇAS', 'FUNGO', 'FUNGOS',
  'BACTÉRIA', 'BACTÉRIAS', 'VÍRUS', 'NEMATOIDE', 'NEMATOIDES',
  'INSETO', 'INSETOS', 'ÁCARO', 'ÁCAROS',
  'PATÓGENO', 'PATÓGENOS', 'VETOR', 'VETORES',
  'SINTOMA', 'SINTOMAS', 'DIAGNOSE',
  'CONTROLE BIOLÓGICO', 'CONTROLE QUÍMICO', 'CONTROLE CULTURAL',
  'MANEJO', 'MANEJAR', 'MANEJANDO', 'MANEJEI',
  'MIP', 'MANEJO INTEGRADO',
  'BIOCONTROLE', 'BIOLÓGICO', 'BIOLÓGICA',
  'MICOLOGIA', 'BACTERIOLOGIA', 'VIROLOGIA',
  'EPIFITIA', 'EPIDEMIOLOGIA',
  'RESISTÊNCIA', 'TOLERÂNCIA', 'SUSCETIBILIDADE',
  'INOCULAÇÃO', 'INOCULO', 'INÓCULO',
  'ESPORULAÇÃO', 'ESPORANGIO', 'ESPORO', 'ESPOROS',
  'MICÉLIO', 'MICELIAL',
  'ENXERTIA', 'ENXERTAR', 'ENXERTANDO', 'ENXERTEI',
  'PROPAGAÇÃO', 'PROPAGAR', 'PROPAGANDO',
  'ADENSAMENTO', 'DENSIDADE', 'ESPAÇAMENTO',
  'MATURAÇÃO', 'AMADURECIMENTO', 'AMADURECER',
  'SENESCÊNCIA', 'DORMÊNCIA',

  // ── Meio ambiente e ciências naturais ─────────────────────────
  'MEIO AMBIENTE', 'AMBIENTE', 'AMBIENTAL',
  'ECOLOGIA', 'ECOLÓGICO', 'ECOLÓGICA',
  'BIODIVERSIDADE', 'FLORA', 'FAUNA',
  'BIOMA', 'BIOMAS', 'CERRADO', 'MATA', 'FLORESTA', 'FLORESTAS',
  'IMPACTO', 'IMPACTOS',
  'SUSTENTABILIDADE', 'SUSTENTÁVEL',
  'COMPOSTAGEM', 'COMPOSTAR', 'COMPOSTANDO', 'COMPOSTEI',
  'RECICLAGEM', 'RECICLAR', 'RECICLANDO', 'RECICLE I',
  'RESÍDUO', 'RESÍDUOS', 'EFLUENTE', 'EFLUENTES',
  'CONTAMINAÇÃO', 'CONTAMINAR', 'CONTAMINANDO', 'CONTAMINEI',
  'BACIA', 'BACIAS', 'RIO', 'RIOS', 'NASCENTE', 'NASCENTES',
  'PRESERVAÇÃO', 'PRESERVAR', 'PRESERVANDO', 'PRESERVEI',
  'CONSERVAÇÃO', 'CONSERVAR', 'CONSERVANDO', 'CONSERVEI',
  'REFLORESTAMENTO', 'REFLORESTAR',

  // ── Verbos de ação geral ───────────────────────────────────────
  'REALIZAR', 'REALIZANDO', 'REALIZEI', 'REALIZADO', 'REALIZAÇÃO',
  'EXECUTAR', 'EXECUTANDO', 'EXECUTEI', 'EXECUTADO', 'EXECUÇÃO',
  'DESENVOLVER', 'DESENVOLVENDO', 'DESENVOLVI', 'DESENVOLVIDO', 'DESENVOLVIMENTO',
  'ELABORAR', 'ELABORANDO', 'ELABOREI', 'ELABORADO', 'ELABORAÇÃO',
  'FINALIZAR', 'FINALIZANDO', 'FINALIZEI', 'FINALIZADO', 'FINALIZAÇÃO',
  'CONCLUIR', 'CONCLUINDO', 'CONCLUÍ', 'CONCLUÍDO', 'CONCLUSÃO',
  'INICIAR', 'INICIANDO', 'INICIEI', 'INICIADO', 'INÍCIO',
  'COMEÇAR', 'COMEÇANDO', 'COMECEI', 'COMEÇADO',
  'PARTICIPAR', 'PARTICIPANDO', 'PARTICIPEI', 'PARTICIPADO', 'PARTICIPAÇÃO',
  'EFETUAR', 'EFETUANDO', 'EFETUEI', 'EFETUADO',
  'REVISAR', 'REVISANDO', 'REVISEI', 'REVISADO', 'REVISÃO',
  'AJUSTAR', 'AJUSTANDO', 'AJUSTEI', 'AJUSTADO', 'AJUSTE', 'AJUSTES',
  'TESTAR', 'TESTANDO', 'TESTEI', 'TESTADO', 'TESTE', 'TESTES',
  'VALIDAR', 'VALIDANDO', 'VALIDEI', 'VALIDADO', 'VALIDAÇÃO',
  'APROVAR', 'APROVANDO', 'APROVEI', 'APROVADO', 'APROVAÇÃO',
  'LEVANTAR', 'LEVANTANDO', 'LEVANTEI', 'LEVANTADO', 'LEVANTAMENTO',
  'MAPEAR', 'MAPEANDO', 'MAPEEI', 'MAPEADO', 'MAPEAMENTO',
  'IDENTIFICAR', 'IDENTIFICANDO', 'IDENTIFIQUEI', 'IDENTIFICADO',
  'SOLICITAR', 'SOLICITANDO', 'SOLICITEI', 'SOLICITADO', 'SOLICITAÇÃO',
  'COMUNICAR', 'COMUNICANDO', 'COMUNIQUEI', 'COMUNICADO', 'COMUNICAÇÃO',
  'INFORMAR', 'INFORMANDO', 'INFORMEI', 'INFORMADO', 'INFORMAÇÃO',
  'CONTATAR', 'CONTATANDO', 'CONTATEI', 'CONTATO',
  'RESPONDER', 'RESPONDENDO', 'RESPONDI', 'RESPONDIDO', 'RESPOSTA',
  'REDIGIR', 'REDIGINDO', 'REDIGI', 'REDIGIDO',
  'INSERIR', 'INSERINDO', 'INSERI', 'INSERIDO',
  'REPARAR', 'REPARANDO', 'REPAREI', 'REPARADO', 'REPARO',
  'CONSERTAR', 'CONSERTANDO', 'CONSERTEI', 'CONSERTADO', 'CONSERTO',
  'SUBSTITUIR', 'SUBSTITUINDO', 'SUBSTITUÍ', 'SUBSTITUÍDO',
  'MOVIMENTAR', 'MOVIMENTANDO', 'MOVIMENTEI', 'MOVIMENTADO',
  'TRANSPORTAR', 'TRANSPORTANDO', 'TRANSPORTEI', 'TRANSPORTADO',
  'PROVIDENCIAR', 'PROVIDENCIANDO', 'PROVIDENCIEI',
  'CHECAR', 'CHECANDO', 'CHEQUEI', 'CHECADO',
  'LEITURA', 'LER', 'LENDO', 'LI', 'LIDO',
  'ESTUDAR', 'ESTUDANDO', 'ESTUDEI', 'ESTUDADO', 'ESTUDO',
  'INSTALAR', 'INSTALANDO', 'INSTALEI', 'INSTALADO',
  'COLETAR', 'COLETANDO', 'COLETEI', 'COLETADO',
  'PROCESSAR', 'PROCESSANDO', 'PROCESSEI', 'PROCESSADO',
  'FORMATAR', 'FORMATANDO', 'FORMATEI', 'FORMATADO',
  'IMPLANTAR', 'IMPLANTANDO', 'IMPLANTEI', 'IMPLANTADO', 'IMPLANTAÇÃO',
  'IMPLEMENTAR', 'IMPLEMENTANDO', 'IMPLEMENTEI', 'IMPLEMENTADO',
  'PROPOR', 'PROPONDO', 'PROPUS', 'PROPOSTO', 'PROPOSTA',
  'PLANEJAR', 'PLANEJANDO', 'PLANEJEI', 'PLANEJADO', 'PLANEJAMENTO',
  'PROGRAMAR', 'PROGRAMANDO', 'PROGRAMEI', 'PROGRAMADO',
  'PRODUZIR', 'PRODUZINDO', 'PRODUZI', 'PRODUZIDO',
  'DESCREVER', 'DESCREVENDO', 'DESCREVI', 'DESCRITO', 'DESCRIÇÃO',
  'DEMONSTRAR', 'DEMONSTRANDO', 'DEMONSTREI', 'DEMONSTRADO',
  'SISTEMATIZAR', 'SISTEMATIZANDO', 'SISTEMATIZEI',
  'PADRONIZAR', 'PADRONIZANDO', 'PADRONIZEI', 'PADRONIZADO',
  'OTIMIZAR', 'OTIMIZANDO', 'OTIMIZEI', 'OTIMIZADO',
  'DIGITALIZAR', 'DIGITALIZANDO', 'DIGITALIZEI', 'DIGITALIZADO',
  'ENCAMINHAR', 'ENCAMINHANDO', 'ENCAMINHEI', 'ENCAMINHADO',
  'DISTRIBUIR', 'DISTRIBUINDO', 'DISTRIBUÍ', 'DISTRIBUÍDO',

  // ── Locais e espaços ───────────────────────────────────────────
  'SECRETARIA',
  'ADMINISTRATIVO', 'ADMINISTRATIVA',
  'GERÊNCIA', 'GERENCIAR', 'GERENCIANDO', 'GERENCIEI',
  'COORDENAÇÃO', 'COORDENAR', 'COORDENANDO', 'COORDENEI',
  'SETOR', 'SETORES',
  'SALA', 'SALAS',
  'ÁREA', 'ÁREAS',
  'COPA', 'COZINHA', 'CANTINA',
  'CORREDOR', 'CORREDORES',
  'BANHEIRO', 'BANHEIROS', 'SANITÁRIO', 'SANITÁRIOS',
  'ALMOXARIFADO',
  'ESCRITÓRIO', 'ESCRITÓRIOS',
  'DEPÓSITO', 'DEPÓSITOS',
  'GALPÃO', 'GALPÕES', 'BARRACÃO', 'BARRACÕES',
  'CÂMARA', 'CÂMARAS',
  'AUDITÓRIO', 'AUDITÓRIOS',
  'RECEPÇÃO', 'HALL',
  'BIBLIOTECA', 'BIBLIOTECAS',
  'BLOCO', 'BLOCOS',
  'CAMPUS', 'INSTITUTO', 'FACULDADE', 'UNIVERSIDADE',
  'DEPARTAMENTO', 'DEPARTAMENTOS',
  'DIRETORIA', 'DIRETORIAS',
  'ESTAÇÃO', 'ESTAÇÕES',

  // ── Tempo ─────────────────────────────────────────────────────
  'MANHÃ', 'TARDE', 'NOITE',
  'DIA', 'DIAS', 'SEMANA', 'SEMANAS', 'MÊS', 'MESES', 'ANO', 'ANOS',
  'TURNO', 'TURNOS', 'PERÍODO', 'PERÍODOS', 'HORÁRIO', 'HORÁRIOS',
  'DIÁRIO', 'DIÁRIA', 'SEMANAL', 'MENSAL', 'ANUAL',
  'SEGUNDA', 'TERÇA', 'QUARTA', 'QUINTA', 'SEXTA', 'SÁBADO', 'DOMINGO',
  'HOJE', 'ONTEM', 'AMANHÃ', 'AGORA', 'ANTES', 'DEPOIS',
  'JANEIRO', 'FEVEREIRO', 'MARÇO', 'ABRIL', 'MAIO', 'JUNHO',
  'JULHO', 'AGOSTO', 'SETEMBRO', 'OUTUBRO', 'NOVEMBRO', 'DEZEMBRO',

  // ── Preposições, artigos e conectivos ─────────────────────────
  'E', 'O', 'A', 'OS', 'AS',
  'DE', 'DO', 'DA', 'DOS', 'DAS',
  'EM', 'NO', 'NA', 'NOS', 'NAS',
  'COM', 'PARA', 'POR', 'AO', 'AOS', 'ÀS',
  'UM', 'UMA', 'UNS', 'UMAS',
  'SE', 'QUE', 'NÃO', 'SIM',
  'MAS', 'MAIS', 'MENOS', 'TAMBÉM', 'ALÉM',
  'QUANDO', 'ONDE', 'COMO', 'PORQUE', 'POIS',
  'ENTRE', 'APÓS', 'ANTES', 'DURANTE',
  'SOBRE', 'SOB', 'ACIMA', 'ABAIXO',
  'JUNTO', 'PRÓXIMO', 'REFERENTE',

  // ── Verbos auxiliares e comuns ─────────────────────────────────
  'FOI', 'FUI', 'ERA', 'FORAM', 'SER', 'ESTAR', 'TEM', 'TINHA',
  'SERÁ', 'SERIA', 'ESTÃO', 'ESTEVE', 'ESTAVAM',
  'FAZER', 'FAZENDO', 'FEZ', 'FEITO',
  'PODER', 'PODE', 'PÔDE', 'PODENDO',
  'DEVER', 'DEVE', 'DEVENDO', 'DEVEU',
  'HAVER', 'HÁ', 'HAVIA', 'HOUVE',
  'IR', 'VAI', 'FOI', 'INDO',
  'VIR', 'VEM', 'VEIO', 'VINDO',
  'DAR', 'DÁ', 'DEU', 'DANDO',
  'VER', 'VÊ', 'VIU', 'VENDO',
  'FICAR', 'FICA', 'FICOU', 'FICANDO',
  'LEVAR', 'LEVA', 'LEVOU', 'LEVANDO',

  // ── Pronomes e determinantes ───────────────────────────────────
  'MEU', 'MINHA', 'MEUS', 'MINHAS',
  'SEU', 'SUA', 'SEUS', 'SUAS',
  'ESTE', 'ESTA', 'ESTES', 'ESTAS',
  'ESSE', 'ESSA', 'ESSES', 'ESSAS',
  'TODO', 'TODA', 'TODOS', 'TODAS',
  'OUTRO', 'OUTRA', 'OUTROS', 'OUTRAS',
  'NOVO', 'NOVA', 'NOVOS', 'NOVAS',
  'LOCAL', 'MESA', 'MESAS', 'BANCADA', 'BANCADAS',
  'MESMO', 'MESMA', 'PRÓPRIO', 'PRÓPRIA',
  'CADA', 'QUALQUER', 'ALGUM', 'ALGUMA',

  // ── Adjetivos e descritores ────────────────────────────────────
  'GERAL', 'GERAIS', 'ESPECÍFICO', 'ESPECÍFICA',
  'TÉCNICO', 'TÉCNICA', 'TÉCNICOS', 'TÉCNICAS',
  'PRÁTICO', 'PRÁTICA', 'PRÁTICOS', 'PRÁTICAS',
  'INTERNO', 'INTERNA', 'EXTERNOS', 'EXTERNAS',
  'MANUAL', 'AUTOMÁTICO', 'AUTOMÁTICA',
  'DIGITAL', 'FÍSICO', 'FÍSICA',
  'CORRETO', 'CORRETA', 'INCORRETO', 'INCORRETA',
  'COMPLETO', 'COMPLETA', 'INCOMPLETO', 'INCOMPLETA',
  'PRINCIPAL', 'SECUNDÁRIO', 'SECUNDÁRIA',
  'INICIAL', 'FINAL', 'PARCIAL',
  'URGENTE', 'PRIORITÁRIO', 'PRIORITÁRIA',
  'PREVENTIVO', 'PREVENTIVA', 'CORRETIVO', 'CORRETIVA',
]

function levenshtein(a: string, b: string): number {
  const m = a.length, n = b.length
  const dp: number[][] = Array.from({ length: m + 1 }, (_, i) =>
    Array.from({ length: n + 1 }, (_, j) => i === 0 ? j : j === 0 ? i : 0)
  )
  for (let i = 1; i <= m; i++)
    for (let j = 1; j <= n; j++)
      dp[i][j] = a[i-1] === b[j-1]
        ? dp[i-1][j-1]
        : 1 + Math.min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1])
  return dp[m][n]
}

const VOCAB_SET = new Set(VOCABULARIO)

function corrigirPalavra(palavra: string): string {
  if (palavra.length <= 2) return palavra
  if (VOCAB_SET.has(palavra)) return palavra
  const limite = palavra.length <= 5 ? 1 : palavra.length <= 8 ? 2 : 3
  let melhor = palavra, menorDist = Infinity
  for (const ref of VOCABULARIO) {
    if (Math.abs(ref.length - palavra.length) > limite) continue
    const d = levenshtein(palavra, ref)
    if (d < menorDist) { menorDist = d; melhor = ref }
    if (d === 0) break
  }
  return menorDist <= limite ? melhor : palavra
}

function corrigirOrtografia(texto: string): string {
  const upper = texto.toUpperCase()
  return upper.split(/(\s+|[^A-ZÁÉÍÓÚÂÊÎÔÛÃÕÀÈÌÒÙÇ]+)/).map(token => {
    if (/^[A-ZÁÉÍÓÚÂÊÎÔÛÃÕÀÈÌÒÙÇ]+$/.test(token)) return corrigirPalavra(token)
    return token
  }).join('')
}

function normalizar(texto: string): string {
  return corrigirOrtografia(texto.trim())
}

export async function POST() {
  try {
    const auth = await requireManager()
    if (!auth.ok) return auth.response

    const db = createSupabaseServiceClient()

    const { data: activities, error } = await db
      .from('activities')
      .select('id, description')

    if (error) return NextResponse.json({ error: error.message }, { status: 500 })
    if (!activities?.length) return NextResponse.json({ updated: 0, message: 'Nenhuma atividade encontrada.' })

    const toUpdate = activities
      .map(a => ({ id: a.id, original: a.description, corrected: normalizar(a.description) }))
      .filter(a => a.original !== a.corrected)

    if (!toUpdate.length) {
      return NextResponse.json({ updated: 0, message: 'Todas as atividades já estão corretas.' })
    }

    const results = await Promise.all(
      toUpdate.map(({ id, corrected }) =>
        db.from('activities').update({ description: corrected }).eq('id', id)
      )
    )

    const errors = results.filter(r => r.error).map(r => r.error?.message)
    if (errors.length) return NextResponse.json({ error: errors.join(', ') }, { status: 500 })

    return NextResponse.json({
      updated: toUpdate.length,
      corrections: toUpdate.map(a => `"${a.original}" → "${a.corrected}"`),
    })
  } catch (err) {
    console.error('[fix-activities-spelling]', err)
    return NextResponse.json({ error: 'Erro interno.' }, { status: 500 })
  }
}
