import { NextResponse } from 'next/server'
import { createSupabaseServiceClient } from '@/lib/supabase/server'
import { requireManager } from '@/lib/route-auth'

const VOCABULARIO: string[] = [
  // ── Limpeza e higiene ──────────────────────────────────────────
  'LIMPEZA', 'LIMPEZAS', 'LIMPAR', 'LIMPANDO', 'LIMPEI', 'LIMPO', 'LIMPA',
  'VARREDURA', 'VARRER', 'VARRENDO', 'VARRI', 'VARRIDO',
  'VASSOURA', 'VASSOURAS', 'VASSOURAR',
  'HIGIENIZAÇÃO', 'HIGIENIZAR', 'HIGIENIZANDO', 'HIGIENIZEI', 'HIGIENIZADO',
  'DESINFECÇÃO', 'DESINFETAR', 'DESINFETANDO', 'DESINFETEI', 'DESINFETADO',
  'DESINFESTAÇÃO', 'DESINFESTANDO', 'DESINFESTEI',
  'ESTERILIZAÇÃO', 'ESTERILIZAR', 'ESTERILIZANDO', 'ESTERILIZEI',
  'LAVAGEM', 'LAVAR', 'LAVANDO', 'LAVEI', 'LAVADO',
  'ENXÁGUE', 'ENXAGUAR', 'ENXAGUANDO', 'ENXAGUEI',
  'FAXINA', 'FAXINANDO', 'FAXINAR', 'FAXINEI',
  'DESCARTE', 'DESCARTANDO', 'DESCARTAR', 'DESCARTEI', 'DESCARTADO',
  'RESÍDUO', 'RESÍDUOS', 'LIXO', 'LIXEIRA', 'LIXEIRAS',
  'DEDETIZAÇÃO', 'DESRATIZAÇÃO', 'SANITIZAÇÃO',
  'ESFREGÃO', 'PANO', 'PANOS', 'RODO', 'BALDE', 'BALDES',
  'DETERGENTE', 'DETERGENTES', 'DESINFETANTE', 'DESINFETANTES',
  'ÁLCOOL', 'HIPOCLORITO', 'CLORO',

  // ── Organização e ordenação ────────────────────────────────────
  'ORGANIZAÇÃO', 'ORGANIZAR', 'ORGANIZANDO', 'ORGANIZEI', 'ORGANIZADO',
  'ARRUMAÇÃO', 'ARRUMAR', 'ARRUMANDO', 'ARRUMEI', 'ARRUMADO',
  'ORDENAÇÃO', 'ORDENAR', 'ORDENANDO', 'ORDENEI', 'ORDENADO',
  'SEPARAÇÃO', 'SEPARAR', 'SEPARANDO', 'SEPAREI', 'SEPARADO',
  'SELEÇÃO', 'SELECIONAR', 'SELECIONANDO', 'SELECIONEI', 'SELECIONADO',
  'TRIAGEM', 'TRIAR', 'TRIANDO', 'TRIEI',
  'MONTAGEM', 'MONTAR', 'MONTANDO', 'MONTEI', 'MONTADO',
  'DESMONTAGEM', 'DESMONTAR', 'DESMONTANDO', 'DESMONTEI',
  'EMPILHAMENTO', 'EMPILHAR', 'EMPILHANDO', 'EMPILHEI',
  'ARMAZENAMENTO', 'ARMAZENAR', 'ARMAZENANDO', 'ARMAZENEI', 'ARMAZENADO',
  'DISPOSIÇÃO', 'DISPOR', 'DISPONDO', 'DISPUS',
  'ALOCAÇÃO', 'ALOCAR', 'ALOCANDO', 'ALOQUEI',
  'ACONDICIONAMENTO', 'ACONDICIONAR', 'ACONDICIONANDO',
  'EMPACOTAMENTO', 'EMPACOTAR', 'EMPACOTANDO', 'EMPACOTEI',

  // ── Atendimento e recepção ─────────────────────────────────────
  'RECEPÇÃO', 'RECEPCIONAR', 'RECEPCIONANDO', 'RECEPCIONEI', 'RECEPCIONADO',
  'ATENDIMENTO', 'ATENDER', 'ATENDENDO', 'ATENDI', 'ATENDIDO',
  'ACOLHIMENTO', 'ACOLHER', 'ACOLHENDO', 'ACOLHI',
  'ORIENTAÇÃO', 'ORIENTAR', 'ORIENTANDO', 'ORIENTEI', 'ORIENTADO',
  'ENCAMINHAMENTO', 'ENCAMINHAR', 'ENCAMINHANDO', 'ENCAMINHEI',
  'SUPORTE', 'APOIO', 'APOIOS',
  'AGENDAMENTO', 'AGENDAR', 'AGENDANDO', 'AGENDEI', 'AGENDADO',
  'VISITA', 'VISITAS', 'VISITAR', 'VISITANDO', 'VISITEI',
  'RECLAMAÇÃO', 'RECLAMAR', 'RECLAMANDO', 'RECLAMEI',
  'DEMANDA', 'DEMANDAS', 'DEMANDAR',
  'USUÁRIO', 'USUÁRIOS', 'CLIENTE', 'CLIENTES',
  'PÚBLICO', 'PROFESSOR', 'PROFESSORES', 'ALUNO', 'ALUNOS',
  'SERVIDOR', 'SERVIDORES', 'FUNCIONÁRIO', 'FUNCIONÁRIOS',
  'VISITANTE', 'VISITANTES', 'PARCEIRO', 'PARCEIROS',

  // ── Documentação e arquivo ─────────────────────────────────────
  'DOCUMENTO', 'DOCUMENTOS', 'DOCUMENTAÇÃO', 'DOCUMENTAR', 'DOCUMENTANDO', 'DOCUMENTADO',
  'ARQUIVAMENTO', 'ARQUIVAR', 'ARQUIVANDO', 'ARQUIVEI', 'ARQUIVADO',
  'ARQUIVO', 'ARQUIVOS', 'PASTA', 'PASTAS',
  'DIGITAÇÃO', 'DIGITAR', 'DIGITANDO', 'DIGITEI', 'DIGITADO',
  'IMPRESSÃO', 'IMPRIMIR', 'IMPRIMINDO', 'IMPRIMI', 'IMPRESSO',
  'CATALOGAÇÃO', 'CATALOGAR', 'CATALOGANDO', 'CATALOGUEI', 'CATALOGADO',
  'PROTOCOLO', 'PROTOCOLANDO', 'PROTOCOLAR', 'PROTOCOLEI', 'PROTOCOLADO',
  'PLANILHA', 'PLANILHAS', 'PLANILHAR', 'PLANILHANDO',
  'RELATÓRIO', 'RELATÓRIOS', 'RELATAR', 'RELATANDO', 'RELATEI',
  'FORMULÁRIO', 'FORMULÁRIOS', 'FORMULAR',
  'FICHA', 'FICHAS', 'FICHÁRIO', 'FICHÁRIOS',
  'CADASTRO', 'CADASTROS', 'CADASTRAR', 'CADASTRANDO', 'CADASTREI', 'CADASTRADO',
  'CADASTRAMENTO',
  'PREENCHIMENTO', 'PREENCHER', 'PREENCHENDO', 'PREENCHEI', 'PREENCHIDO',
  'VERIFICAÇÃO', 'VERIFICAR', 'VERIFICANDO', 'VERIFIQUEI', 'VERIFICADO',
  'CONFERÊNCIA', 'CONFERIR', 'CONFERINDO', 'CONFERI', 'CONFERIDO',
  'CLASSIFICAÇÃO', 'CLASSIFICAR', 'CLASSIFICANDO', 'CLASSIFIQUEI', 'CLASSIFICADO',
  'RECEBIMENTO', 'RECEBER', 'RECEBENDO', 'RECEBI', 'RECEBIDO',
  'ENTREGA', 'ENTREGAR', 'ENTREGANDO', 'ENTREGEI', 'ENTREGUE',
  'ENVIO', 'ENVIAR', 'ENVIANDO', 'ENVIEI', 'ENVIADO',
  'EMISSÃO', 'EMITIR', 'EMITINDO', 'EMITI', 'EMITIDO',
  'CONTROLE', 'CONTROLAR', 'CONTROLANDO', 'CONTROLEI', 'CONTROLADO',
  'REGISTRO', 'REGISTROS', 'REGISTRAR', 'REGISTRANDO', 'REGISTREI', 'REGISTRADO',
  'ASSINATURA', 'ASSINAR', 'ASSINANDO', 'ASSINEI', 'ASSINADO',
  'CÓPIA', 'CÓPIAS', 'COPIAR', 'COPIANDO', 'COPIEI', 'COPIADO',
  'XEROX', 'XEROCAR', 'XEROCANDO', 'XEROQUEI',
  'DIGITALIZAÇÃO', 'DIGITALIZAR', 'DIGITALIZANDO', 'DIGITALIZEI', 'DIGITALIZADO',
  'ESCANEAMENTO', 'ESCANEAR', 'ESCANEANDO', 'ESCANEEI', 'ESCANEADO',
  'LANÇAMENTO', 'LANÇAR', 'LANÇANDO', 'LANCEI', 'LANÇADO',
  'ANOTAÇÃO', 'ANOTAÇÕES', 'ANOTAR', 'ANOTANDO', 'ANOTEI', 'ANOTADO',
  'TRANSCRIÇÃO', 'TRANSCREVER', 'TRANSCREVENDO', 'TRANSCREVI',
  'CONTRATO', 'CONTRATOS', 'TERMO', 'TERMOS', 'DECLARAÇÃO', 'DECLARAÇÕES',
  'OFÍCIO', 'OFÍCIOS', 'MEMORANDO', 'MEMORANDOS', 'ATA', 'ATAS',
  'PORTARIA', 'PORTARIAS', 'EDITAL', 'EDITAIS', 'PROCESSO', 'PROCESSOS',
  'NORMA', 'NORMAS', 'MANUAL', 'MANUAIS', 'INSTRUÇÃO', 'INSTRUÇÕES',

  // ── Reuniões e capacitação ─────────────────────────────────────
  'REUNIÃO', 'REUNIÕES', 'REUNIR', 'REUNINDO', 'REUNI', 'REUNIDO',
  'TREINAMENTO', 'TREINAMENTOS', 'TREINAR', 'TREINANDO', 'TREINEI', 'TREINADO',
  'CAPACITAÇÃO', 'CAPACITAR', 'CAPACITANDO', 'CAPACITEI', 'CAPACITADO',
  'CURSO', 'CURSOS', 'CURSANDO', 'CURSEI',
  'PALESTRA', 'PALESTRAS', 'PALESTRAR', 'PALESTRANDO',
  'APRESENTAÇÃO', 'APRESENTAÇÕES', 'APRESENTAR', 'APRESENTANDO', 'APRESENTEI', 'APRESENTADO',
  'WORKSHOP', 'WORKSHOPS', 'SEMINÁRIO', 'SEMINÁRIOS',
  'INSTRUÇÃO', 'INSTRUIR', 'INSTRUINDO', 'INSTRUÍ', 'INSTRUÍDO',
  'DEBATE', 'DEBATES', 'DEBATER', 'DEBATENDO', 'DEBATI',
  'DISCUSSÃO', 'DISCUSSÕES', 'DISCUTIR', 'DISCUTINDO', 'DISCUTI',
  'AULA', 'AULAS', 'MINISTRAR', 'MINISTRANDO', 'MINISTREI',
  'DISCIPLINA', 'DISCIPLINAS', 'MÓDULO', 'MÓDULOS',
  'CERTIFICADO', 'CERTIFICADOS', 'CERTIFICAÇÃO',
  'EVENTO', 'EVENTOS', 'CONGRESSO', 'CONGRESSOS', 'SIMPÓSIO', 'SIMPÓSIOS',
  'CONFERÊNCIA', 'CONFERÊNCIAS',

  // ── Monitoramento e supervisão ─────────────────────────────────
  'MONITORAMENTO', 'MONITORAR', 'MONITORANDO', 'MONITOREI', 'MONITORADO',
  'ACOMPANHAMENTO', 'ACOMPANHAR', 'ACOMPANHANDO', 'ACOMPANHEI', 'ACOMPANHADO',
  'SUPERVISÃO', 'SUPERVISIONAR', 'SUPERVISIONANDO', 'SUPERVISIONEI',
  'COLABORAÇÃO', 'COLABORAR', 'COLABORANDO', 'COLABOREI', 'COLABORADO',
  'AUXILIAR', 'AUXILIANDO', 'AUXILIEI', 'AUXILIADO',
  'AJUDAR', 'AJUDANDO', 'AJUDEI', 'AJUDADO',
  'APOIAR', 'APOIANDO', 'APOIEI', 'APOIADO',
  'FISCALIZAÇÃO', 'FISCALIZAR', 'FISCALIZANDO', 'FISCALIZEI',
  'AUDITORIA', 'AUDITAR', 'AUDITANDO', 'AUDITEI',
  'AVALIAÇÃO', 'AVALIAR', 'AVALIANDO', 'AVALIEI', 'AVALIADO',
  'FEEDBACK', 'RELATORIA', 'INDICADOR', 'INDICADORES',
  'DIAGNÓSTICO', 'DIAGNOSTICAR', 'DIAGNOSTICANDO',
  'OBSERVAÇÃO', 'OBSERVAÇÕES', 'OBSERVAR', 'OBSERVANDO', 'OBSERVEI',

  // ── Estoque e suprimentos ──────────────────────────────────────
  'ESTOQUE', 'ESTOCAR', 'ESTOCANDO', 'ESTOQUEI', 'ESTOCADO',
  'MATERIAL', 'MATERIAIS',
  'SUPRIMENTO', 'SUPRIMENTOS', 'SUPRIR', 'SUPRINDO', 'SUPRI',
  'INSUMO', 'INSUMOS',
  'INVENTÁRIO', 'INVENTARIAR', 'INVENTARIANDO', 'INVENTARIEI',
  'REQUISIÇÃO', 'REQUISIÇÕES', 'REQUISITAR', 'REQUISITANDO', 'REQUISITEI',
  'COMPRAS', 'COMPRAR', 'COMPRANDO', 'COMPREI', 'COMPRADO',
  'REPOSIÇÃO', 'REPOR', 'REPONDO', 'REPUS', 'REPOSTO',
  'ETIQUETAGEM', 'ETIQUETAR', 'ETIQUETANDO', 'ETIQUETEI', 'ETIQUETADO',
  'ETIQUETA', 'ETIQUETAS',
  'CONTAGEM', 'CONTAR', 'CONTANDO', 'CONTEI', 'CONTADO',
  'PEDIDO', 'PEDIDOS', 'PEDIR', 'PEDINDO', 'PEDI',
  'FORNECIMENTO', 'FORNECEDOR', 'FORNECEDORES', 'FORNECER', 'FORNECENDO',
  'PRODUTO', 'PRODUTOS', 'ITEM', 'ITENS',
  'CONSUMÍVEL', 'CONSUMÍVEIS', 'INSUMOS',
  'RECEBIMENTO', 'NOTA', 'NOTAS', 'FATURA', 'FATURAS',
  'DEVOLUÇÃO', 'DEVOLVER', 'DEVOLVENDO', 'DEVOLVI',

  // ── Informática e tecnologia ───────────────────────────────────
  'INFORMÁTICA',
  'COMPUTADOR', 'COMPUTADORES', 'NOTEBOOK', 'NOTEBOOKS',
  'SISTEMA', 'SISTEMAS',
  'IMPRESSORA', 'IMPRESSORAS', 'SCANNER', 'SCANNERS',
  'EQUIPAMENTO', 'EQUIPAMENTOS',
  'MANUTENÇÃO', 'MANUTENÇÕES', 'MANTER', 'MANTENDO', 'MANTIVE', 'MANTIDO',
  'INSTALAÇÃO', 'INSTALAR', 'INSTALANDO', 'INSTALEI', 'INSTALADO',
  'CONFIGURAÇÃO', 'CONFIGURAR', 'CONFIGURANDO', 'CONFIGUREI', 'CONFIGURADO',
  'ATUALIZAÇÃO', 'ATUALIZAR', 'ATUALIZANDO', 'ATUALIZEI', 'ATUALIZADO',
  'ACESSO', 'ACESSAR', 'ACESSANDO', 'ACESSEI', 'ACESSADO',
  'BACKUP', 'BACKUPS',
  'REDE', 'REDES', 'INTERNET', 'SERVIDOR', 'SERVIDORES',
  'HARDWARE', 'SOFTWARE', 'APLICATIVO', 'APLICATIVOS',
  'SUPORTE', 'TÉCNICO', 'TÉCNICA',
  'CÂMERA', 'CÂMERAS', 'PROJETOR', 'PROJETORES',
  'TABLET', 'CELULAR', 'CELULARES', 'TELEFONE', 'TELEFONES',
  'EMAIL', 'E-MAIL', 'MENSAGEM', 'MENSAGENS',
  'SENHA', 'SENHAS', 'LOGIN', 'USUÁRIO', 'USUÁRIOS',

  // ── Laboratório geral ──────────────────────────────────────────
  'LABORATÓRIO', 'LABORATÓRIOS', 'LAB',
  'ANÁLISE', 'ANÁLISES', 'ANALISAR', 'ANALISANDO', 'ANALISEI', 'ANALISADO',
  'AMOSTRA', 'AMOSTRAS', 'AMOSTRAR', 'AMOSTRANDO', 'AMOSTREI',
  'EXPERIMENTO', 'EXPERIMENTOS', 'EXPERIMENTAR', 'EXPERIMENTANDO', 'EXPERIMENTEI',
  'PESQUISA', 'PESQUISAS', 'PESQUISAR', 'PESQUISANDO', 'PESQUISEI', 'PESQUISADO',
  'COLETA', 'COLETAS', 'COLETAR', 'COLETANDO', 'COLETEI', 'COLETADO',
  'MEDIÇÃO', 'MEDIÇÕES', 'MEDIR', 'MEDINDO', 'MEDI', 'MEDIDO',
  'PESAGEM', 'PESAR', 'PESANDO', 'PESEI', 'PESADO',
  'CALIBRAÇÃO', 'CALIBRAR', 'CALIBRANDO', 'CALIBREI', 'CALIBRADO',
  'PREPARAÇÃO', 'PREPARAR', 'PREPARANDO', 'PREPAREI', 'PREPARADO',
  'PREPARO', 'PREPAR',
  'MISTURA', 'MISTURAS', 'MISTURAR', 'MISTURANDO', 'MISTUREI', 'MISTURADO',
  'SOLUÇÃO', 'SOLUÇÕES', 'DILUIÇÃO', 'DILUIR', 'DILUINDO', 'DILUÍ',
  'REAGENTE', 'REAGENTES', 'SUBSTÂNCIA', 'SUBSTÂNCIAS',
  'VIDRARIA', 'VIDRARIAS', 'PIPETA', 'PIPETAS', 'BURETA', 'BURETAS',
  'BÉQUER', 'BÉQUERES', 'ERLENMEYER', 'PROVETA', 'PROVETAS',
  'RESULTADO', 'RESULTADOS',
  'LAUDO', 'LAUDOS', 'LAUDO TÉCNICO',
  'EXAME', 'EXAMES',
  'INSPEÇÃO', 'INSPEÇÕES', 'INSPECIONAR', 'INSPECIONANDO', 'INSPECIONEI',
  'VISTORIA', 'VISTORIAS', 'VISTORIAR', 'VISTORIANDO', 'VISTORIEI',
  'MICROSCÓPIO', 'MICROSCÓPIOS', 'LÂMINA', 'LÂMINAS', 'LAMÍNULA',
  'CENTRÍFUGA', 'CENTRIFUGAR', 'CENTRÍFUGAS', 'CENTRÍFUGANDO',
  'AUTOCLAVE', 'AUTOCLAVAR', 'AUTOCLAVANDO',
  'BALANÇA', 'BALANÇAS', 'PESAR', 'AFERIÇÃO',
  'ESTUFA', 'ESTUFAS', 'INCUBADORA', 'INCUBADORAS',
  'AGITADOR', 'AGITAR', 'AGITANDO', 'AGITEI',
  'EXTRAÇÃO', 'EXTRAIR', 'EXTRAINDO', 'EXTRAÍ', 'EXTRAÍDO',
  'FILTRAÇÃO', 'FILTRAR', 'FILTRANDO', 'FILTREI', 'FILTRADO',
  'TITULAÇÃO', 'TITULAR', 'TITULANDO', 'TITULEI',
  'CONCENTRAÇÃO', 'CONCENTRAR', 'CONCENTRANDO', 'CONCENTREI',
  'INOCULAÇÃO', 'INOCULAR', 'INOCULANDO', 'INOCULEI',
  'CULTURA', 'CULTURAS', 'MEIO', 'MEIOS', 'CALDO', 'CALDOS',
  'PLACA', 'PLACAS', 'PETRI', 'SEMEADURA', 'SEMEAR', 'SEMEANDO',
  'REPIQUE', 'REPICAR', 'REPICANDO', ' REPIQUEI',
  'ISOLAMENTO', 'ISOLAR', 'ISOLANDO', 'ISOLEI', 'ISOLADO',
  'IDENTIFICAÇÃO', 'IDENTIFICAR', 'IDENTIFICANDO', 'IDENTIFIQUEI',
  'COLORAÇÃO', 'COLORIR', 'COLORINDO', 'COLORAÇÃO',
  'GRAM', 'COLORAÇÃO DE GRAM',
  'CROMATOGRAFIA', 'ESPECTROFOTOMETRIA', 'ESPECTROSCOPIA',
  'ABSORBÂNCIA', 'ABSORBÂNCIA', 'LEITURA',
  'PH', 'ACIDEZ', 'ALCALINIDADE', 'UMIDADE', 'TEMPERATURA',
  'CONCENTRAÇÃO', 'DIÂMETRO', 'COMPRIMENTO', 'LARGURA', 'ALTURA',
  'VOLUME', 'MASSA', 'PESO', 'DENSIDADE', 'VISCOSIDADE',

  // ── Agronomia e agricultura ────────────────────────────────────
  'AGRONOMIA', 'AGRONÔMICO', 'AGRONÔMICA',
  'SOLO', 'SOLOS', 'TERRA', 'TERRAS', 'SUBST RATO', 'SUBSTRATO', 'SUBSTRATOS',
  'PLANTA', 'PLANTAS', 'PLANTIO', 'PLANTIOS', 'PLANTAR', 'PLANTANDO', 'PLANTEI',
  'CULTURA', 'CULTURAS', 'CULTIVAR', 'CULTIVANDO', 'CULTIVEI', 'CULTIVO', 'CULTIVOS',
  'SEMEADURA', 'SEMEAR', 'SEMEANDO', 'SEMEEI',
  'SEMENTE', 'SEMENTES',
  'GERMINAÇÃO', 'GERMINAR', 'GERMINANDO', 'GERMINEI',
  'MUDA', 'MUDAS',
  'PODA', 'PODAS', 'PODAR', 'PODANDO', 'PODEI',
  'ADUBAÇÃO', 'ADUBAR', 'ADUBANDO', 'ADUBEI', 'ADUBADO',
  'ADUBO', 'ADUBOS', 'FERTILIZANTE', 'FERTILIZANTES',
  'FERTILIZAÇÃO', 'FERTILIZAR', 'FERTILIZANDO', 'FERTILIZEI',
  'IRRIGAÇÃO', 'IRRIGAR', 'IRRIGANDO', 'IRRIGANDO', 'IRRIGADO',
  'ÁGUA', 'ÁGUAS', 'MOLHAR', 'MOLHANDO', 'MOLHEI',
  'DRENAGEM', 'DRENAR', 'DRENANDO', 'DRENEI',
  'HERBICIDA', 'HERBICIDAS', 'PESTICIDA', 'PESTICIDAS',
  'DEFENSIVO', 'DEFENSIVOS', 'AGROTÓXICO', 'AGROTÓXICOS',
  'FUNGICIDA', 'FUNGICIDAS', 'INSETICIDA', 'INSETICIDAS',
  'APLICAÇÃO', 'APLICAR', 'APLICANDO', 'APLIQUEI', 'APLICADO',
  'PULVERIZAÇÃO', 'PULVERIZAR', 'PULVERIZANDO', 'PULVERIZEI',
  'CALAGEM', 'CALCÁRIO', 'CALAGEM DO SOLO',
  'CORREÇÃO', 'CORRIGIR', 'CORRIGINDO', 'CORRIGI',
  'ANÁLISE DE SOLO', 'ANALISE DE SOLO',
  'COLHEITA', 'COLHEITAS', 'COLHER', 'COLHENDO', 'COLHI', 'COLHIDO',
  'PRODUÇÃO', 'PRODUZIR', 'PRODUZINDO', 'PRODUZI', 'PRODUZIDO',
  'PRODUTIVIDADE',
  'SAFRA', 'SAFRAS',
  'CAMPO', 'CAMPOS',
  'PARCELA', 'PARCELAS',
  'TALHÃO', 'TALHÕES',
  'ESTUFA', 'ESTUFAS', 'CASA DE VEGETAÇÃO',
  'VIVEIRO', 'VIVEIROS',
  'HORTA', 'HORTAS',
  'POMAR', 'POMARES',
  'RAIZ', 'RAÍZES', 'CAULE', 'CAULES', 'FOLHA', 'FOLHAS', 'FRUTO', 'FRUTOS',
  'FLOR', 'FLORES', 'ESPIGA', 'ESPIGAS', 'GRÃO', 'GRÃOS',
  'SOJA', 'MILHO', 'FEIJÃO', 'ARROZ', 'CANA', 'ALGODÃO',
  'CAFÉ', 'EUCALIPTO', 'TOMATE', 'TRIGO', 'SORGO',
  'PASTAGEM', 'PASTO', 'FORRAGEM', 'FORRAGEIRA',
  'GADO', 'BOVINO', 'OVINO', 'SUÍNO', 'AVES',
  'FITOPATOLOGIA', 'ENTOMOLOGIA', 'FITOPATOLÓGICO',
  'PRAGA', 'PRAGAS', 'DOENÇA', 'DOENÇAS', 'FUNGO', 'FUNGOS',
  'BACTÉRIA', 'BACTÉRIAS', 'VÍRUS', 'NEMATOIDE', 'NEMATOIDES',
  'INSETO', 'INSETOS', 'ÁCARO', 'ÁCAROS',
  'PATÓGENO', 'PATÓGENOS', 'VETOR', 'VETORES',
  'SINTOMA', 'SINTOMAS', 'DIAGNOSE',
  'CONTROLE BIOLÓGICO', 'CONTROLE QUÍMICO', 'CONTROLE CULTURAL',
  'MANEJO', 'MANEJAR', 'MANEJANDO', 'MANEJEI',
  'MIP', 'MANEJO INTEGRADO',
  'BIOCONTROLE', 'BIOLÓGICO', 'BIOLÓGICA',
  'MICOLOGIA', 'BACTERIOLOGIA', 'VIROLOGIA',
  'EPIFITIA', 'EPIDEMIOLOGIA',
  'RESISTÊNCIA', 'TOLERÂNCIA', 'SUSCETIBILIDADE',
  'INOCULAÇÃO', 'INOCULO', 'INÓCULO',
  'ESPORULAÇÃO', 'ESPORANGIO', 'ESPORO', 'ESPOROS',
  'MICÉLIO', 'MICELIAL',
  'ENXERTIA', 'ENXERTAR', 'ENXERTANDO', 'ENXERTEI',
  'PROPAGAÇÃO', 'PROPAGAR', 'PROPAGANDO',
  'ADENSAMENTO', 'DENSIDADE', 'ESPAÇAMENTO',
  'MATURAÇÃO', 'AMADURECIMENTO', 'AMADURECER',
  'SENESCÊNCIA', 'DORMÊNCIA',

  // ── Meio ambiente e ciências naturais ─────────────────────────
  'MEIO AMBIENTE', 'AMBIENTE', 'AMBIENTAL',
  'ECOLOGIA', 'ECOLÓGICO', 'ECOLÓGICA',
  'BIODIVERSIDADE', 'FLORA', 'FAUNA',
  'BIOMA', 'BIOMAS', 'CERRADO', 'MATA', 'FLORESTA', 'FLORESTAS',
  'IMPACTO', 'IMPACTOS',
  'SUSTENTABILIDADE', 'SUSTENTÁVEL',
  'COMPOSTAGEM', 'COMPOSTAR', 'COMPOSTANDO', 'COMPOSTEI',
  'RECICLAGEM', 'RECICLAR', 'RECICLANDO', 'RECICLE I',
  'RESÍDUO', 'RESÍDUOS', 'EFLUENTE', 'EFLUENTES',
  'CONTAMINAÇÃO', 'CONTAMINAR', 'CONTAMINANDO', 'CONTAMINEI',
  'BACIA', 'BACIAS', 'RIO', 'RIOS', 'NASCENTE', 'NASCENTES',
  'PRESERVAÇÃO', 'PRESERVAR', 'PRESERVANDO', 'PRESERVEI',
  'CONSERVAÇÃO', 'CONSERVAR', 'CONSERVANDO', 'CONSERVEI',
  'REFLORESTAMENTO', 'REFLORESTAR',

  // ── Verbos de ação geral ───────────────────────────────────────
  'REALIZAR', 'REALIZANDO', 'REALIZEI', 'REALIZADO', 'REALIZAÇÃO',
  'EXECUTAR', 'EXECUTANDO', 'EXECUTEI', 'EXECUTADO', 'EXECUÇÃO',
  'DESENVOLVER', 'DESENVOLVENDO', 'DESENVOLVI', 'DESENVOLVIDO', 'DESENVOLVIMENTO',
  'ELABORAR', 'ELABORANDO', 'ELABOREI', 'ELABORADO', 'ELABORAÇÃO',
  'FINALIZAR', 'FINALIZANDO', 'FINALIZEI', 'FINALIZADO', 'FINALIZAÇÃO',
  'CONCLUIR', 'CONCLUINDO', 'CONCLUÍ', 'CONCLUÍDO', 'CONCLUSÃO',
  'INICIAR', 'INICIANDO', 'INICIEI', 'INICIADO', 'INÍCIO',
  'COMEÇAR', 'COMEÇANDO', 'COMECEI', 'COMEÇADO',
  'PARTICIPAR', 'PARTICIPANDO', 'PARTICIPEI', 'PARTICIPADO', 'PARTICIPAÇÃO',
  'EFETUAR', 'EFETUANDO', 'EFETUEI', 'EFETUADO',
  'REVISAR', 'REVISANDO', 'REVISEI', 'REVISADO', 'REVISÃO',
  'AJUSTAR', 'AJUSTANDO', 'AJUSTEI', 'AJUSTADO', 'AJUSTE', 'AJUSTES',
  'TESTAR', 'TESTANDO', 'TESTEI', 'TESTADO', 'TESTE', 'TESTES',
  'VALIDAR', 'VALIDANDO', 'VALIDEI', 'VALIDADO', 'VALIDAÇÃO',
  'APROVAR', 'APROVANDO', 'APROVEI', 'APROVADO', 'APROVAÇÃO',
  'LEVANTAR', 'LEVANTANDO', 'LEVANTEI', 'LEVANTADO', 'LEVANTAMENTO',
  'MAPEAR', 'MAPEANDO', 'MAPEEI', 'MAPEADO', 'MAPEAMENTO',
  'IDENTIFICAR', 'IDENTIFICANDO', 'IDENTIFIQUEI', 'IDENTIFICADO',
  'SOLICITAR', 'SOLICITANDO', 'SOLICITEI', 'SOLICITADO', 'SOLICITAÇÃO',
  'COMUNICAR', 'COMUNICANDO', 'COMUNIQUEI', 'COMUNICADO', 'COMUNICAÇÃO',
  'INFORMAR', 'INFORMANDO', 'INFORMEI', 'INFORMADO', 'INFORMAÇÃO',
  'CONTATAR', 'CONTATANDO', 'CONTATEI', 'CONTATO',
  'RESPONDER', 'RESPONDENDO', 'RESPONDI', 'RESPONDIDO', 'RESPOSTA',
  'REDIGIR', 'REDIGINDO', 'REDIGI', 'REDIGIDO',
  'INSERIR', 'INSERINDO', 'INSERI', 'INSERIDO',
  'REPARAR', 'REPARANDO', 'REPAREI', 'REPARADO', 'REPARO',
  'CONSERTAR', 'CONSERTANDO', 'CONSERTEI', 'CONSERTADO', 'CONSERTO',
  'SUBSTITUIR', 'SUBSTITUINDO', 'SUBSTITUÍ', 'SUBSTITUÍDO',
  'MOVIMENTAR', 'MOVIMENTANDO', 'MOVIMENTEI', 'MOVIMENTADO',
  'TRANSPORTAR', 'TRANSPORTANDO', 'TRANSPORTEI', 'TRANSPORTADO',
  'PROVIDENCIAR', 'PROVIDENCIANDO', 'PROVIDENCIEI',
  'CHECAR', 'CHECANDO', 'CHEQUEI', 'CHECADO',
  'LEITURA', 'LER', 'LENDO', 'LI', 'LIDO',
  'ESTUDAR', 'ESTUDANDO', 'ESTUDEI', 'ESTUDADO', 'ESTUDO',
  'INSTALAR', 'INSTALANDO', 'INSTALEI', 'INSTALADO',
  'COLETAR', 'COLETANDO', 'COLETEI', 'COLETADO',
  'PROCESSAR', 'PROCESSANDO', 'PROCESSEI', 'PROCESSADO',
  'FORMATAR', 'FORMATANDO', 'FORMATEI', 'FORMATADO',
  'IMPLANTAR', 'IMPLANTANDO', 'IMPLANTEI', 'IMPLANTADO', 'IMPLANTAÇÃO',
  'IMPLEMENTAR', 'IMPLEMENTANDO', 'IMPLEMENTEI', 'IMPLEMENTADO',
  'PROPOR', 'PROPONDO', 'PROPUS', 'PROPOSTO', 'PROPOSTA',
  'PLANEJAR', 'PLANEJANDO', 'PLANEJEI', 'PLANEJADO', 'PLANEJAMENTO',
  'PROGRAMAR', 'PROGRAMANDO', 'PROGRAMEI', 'PROGRAMADO',
  'PRODUZIR', 'PRODUZINDO', 'PRODUZI', 'PRODUZIDO',
  'DESCREVER', 'DESCREVENDO', 'DESCREVI', 'DESCRITO', 'DESCRIÇÃO',
  'DEMONSTRAR', 'DEMONSTRANDO', 'DEMONSTREI', 'DEMONSTRADO',
  'SISTEMATIZAR', 'SISTEMATIZANDO', 'SISTEMATIZEI',
  'PADRONIZAR', 'PADRONIZANDO', 'PADRONIZEI', 'PADRONIZADO',
  'OTIMIZAR', 'OTIMIZANDO', 'OTIMIZEI', 'OTIMIZADO',
  'DIGITALIZAR', 'DIGITALIZANDO', 'DIGITALIZEI', 'DIGITALIZADO',
  'ENCAMINHAR', 'ENCAMINHANDO', 'ENCAMINHEI', 'ENCAMINHADO',
  'DISTRIBUIR', 'DISTRIBUINDO', 'DISTRIBUÍ', 'DISTRIBUÍDO',

  // ── Locais e espaços ───────────────────────────────────────────
  'SECRETARIA',
  'ADMINISTRATIVO', 'ADMINISTRATIVA',
  'GERÊNCIA', 'GERENCIAR', 'GERENCIANDO', 'GERENCIEI',
  'COORDENAÇÃO', 'COORDENAR', 'COORDENANDO', 'COORDENEI',
  'SETOR', 'SETORES',
  'SALA', 'SALAS',
  'ÁREA', 'ÁREAS',
  'COPA', 'COZINHA', 'CANTINA',
  'CORREDOR', 'CORREDORES',
  'BANHEIRO', 'BANHEIROS', 'SANITÁRIO', 'SANITÁRIOS',
  'ALMOXARIFADO',
  'ESCRITÓRIO', 'ESCRITÓRIOS',
  'DEPÓSITO', 'DEPÓSITOS',
  'GALPÃO', 'GALPÕES', 'BARRACÃO', 'BARRACÕES',
  'CÂMARA', 'CÂMARAS',
  'AUDITÓRIO', 'AUDITÓRIOS',
  'RECEPÇÃO', 'HALL',
  'BIBLIOTECA', 'BIBLIOTECAS',
  'BLOCO', 'BLOCOS',
  'CAMPUS', 'INSTITUTO', 'FACULDADE', 'UNIVERSIDADE',
  'DEPARTAMENTO', 'DEPARTAMENTOS',
  'DIRETORIA', 'DIRETORIAS',
  'ESTAÇÃO', 'ESTAÇÕES',

  // ── Tempo ─────────────────────────────────────────────────────
  'MANHÃ', 'TARDE', 'NOITE',
  'DIA', 'DIAS', 'SEMANA', 'SEMANAS', 'MÊS', 'MESES', 'ANO', 'ANOS',
  'TURNO', 'TURNOS', 'PERÍODO', 'PERÍODOS', 'HORÁRIO', 'HORÁRIOS',
  'DIÁRIO', 'DIÁRIA', 'SEMANAL', 'MENSAL', 'ANUAL',
  'SEGUNDA', 'TERÇA', 'QUARTA', 'QUINTA', 'SEXTA', 'SÁBADO', 'DOMINGO',
  'HOJE', 'ONTEM', 'AMANHÃ', 'AGORA', 'ANTES', 'DEPOIS',
  'JANEIRO', 'FEVEREIRO', 'MARÇO', 'ABRIL', 'MAIO', 'JUNHO',
  'JULHO', 'AGOSTO', 'SETEMBRO', 'OUTUBRO', 'NOVEMBRO', 'DEZEMBRO',

  // ── Preposições, artigos e conectivos ─────────────────────────
  'E', 'O', 'A', 'OS', 'AS',
  'DE', 'DO', 'DA', 'DOS', 'DAS',
  'EM', 'NO', 'NA', 'NOS', 'NAS',
  'COM', 'PARA', 'POR', 'AO', 'AOS', 'ÀS',
  'UM', 'UMA', 'UNS', 'UMAS',
  'SE', 'QUE', 'NÃO', 'SIM',
  'MAS', 'MAIS', 'MENOS', 'TAMBÉM', 'ALÉM',
  'QUANDO', 'ONDE', 'COMO', 'PORQUE', 'POIS',
  'ENTRE', 'APÓS', 'ANTES', 'DURANTE',
  'SOBRE', 'SOB', 'ACIMA', 'ABAIXO',
  'JUNTO', 'PRÓXIMO', 'REFERENTE',

  // ── Verbos auxiliares e comuns ─────────────────────────────────
  'FOI', 'FUI', 'ERA', 'FORAM', 'SER', 'ESTAR', 'TEM', 'TINHA',
  'SERÁ', 'SERIA', 'ESTÃO', 'ESTEVE', 'ESTAVAM',
  'FAZER', 'FAZENDO', 'FEZ', 'FEITO',
  'PODER', 'PODE', 'PÔDE', 'PODENDO',
  'DEVER', 'DEVE', 'DEVENDO', 'DEVEU',
  'HAVER', 'HÁ', 'HAVIA', 'HOUVE',
  'IR', 'VAI', 'FOI', 'INDO',
  'VIR', 'VEM', 'VEIO', 'VINDO',
  'DAR', 'DÁ', 'DEU', 'DANDO',
  'VER', 'VÊ', 'VIU', 'VENDO',
  'FICAR', 'FICA', 'FICOU', 'FICANDO',
  'LEVAR', 'LEVA', 'LEVOU', 'LEVANDO',

  // ── Pronomes e determinantes ───────────────────────────────────
  'MEU', 'MINHA', 'MEUS', 'MINHAS',
  'SEU', 'SUA', 'SEUS', 'SUAS',
  'ESTE', 'ESTA', 'ESTES', 'ESTAS',
  'ESSE', 'ESSA', 'ESSES', 'ESSAS',
  'TODO', 'TODA', 'TODOS', 'TODAS',
  'OUTRO', 'OUTRA', 'OUTROS', 'OUTRAS',
  'NOVO', 'NOVA', 'NOVOS', 'NOVAS',
  'LOCAL', 'MESA', 'MESAS', 'BANCADA', 'BANCADAS',
  'MESMO', 'MESMA', 'PRÓPRIO', 'PRÓPRIA',
  'CADA', 'QUALQUER', 'ALGUM', 'ALGUMA',

  // ── Adjetivos e descritores ────────────────────────────────────
  'GERAL', 'GERAIS', 'ESPECÍFICO', 'ESPECÍFICA',
  'TÉCNICO', 'TÉCNICA', 'TÉCNICOS', 'TÉCNICAS',
  'PRÁTICO', 'PRÁTICA', 'PRÁTICOS', 'PRÁTICAS',
  'INTERNO', 'INTERNA', 'EXTERNOS', 'EXTERNAS',
  'MANUAL', 'AUTOMÁTICO', 'AUTOMÁTICA',
  'DIGITAL', 'FÍSICO', 'FÍSICA',
  'CORRETO', 'CORRETA', 'INCORRETO', 'INCORRETA',
  'COMPLETO', 'COMPLETA', 'INCOMPLETO', 'INCOMPLETA',
  'PRINCIPAL', 'SECUNDÁRIO', 'SECUNDÁRIA',
  'INICIAL', 'FINAL', 'PARCIAL',
  'URGENTE', 'PRIORITÁRIO', 'PRIORITÁRIA',
  'PREVENTIVO', 'PREVENTIVA', 'CORRETIVO', 'CORRETIVA',

  // ── Conjugações completas — verbos de alta frequência ─────────
  // FAZER
  'FAZER','FAÇO','FAZ','FAZEMOS','FAZEM','FAZIA','FAZIAS','FAZÍAMOS','FAZIAM',
  'FIZ','FEZ','FIZEMOS','FIZERAM','FIZERA','FIZESSE','FAREI','FARÁ','FAREMOS',
  'FARÃO','FARIA','FEITO','FEITA','FEITOS','FEITAS',
  // PODER
  'PODER','POSSO','PODE','PODEMOS','PODEM','PODIA','PODÍAMOS','PODIAM',
  'PUDE','PÔDE','PUDEMOS','PUDERAM','PUDESSE','PODEREI','PODERÁ','PODERÍAMOS',
  'PODENDO','PODIDO',
  // DEVER
  'DEVER','DEVO','DEVE','DEVEMOS','DEVEM','DEVIA','DEVÍAMOS','DEVIAM',
  'DEVEREI','DEVERÁ','DEVERIA','DEVENDO','DEVIDO',
  // TER
  'TER','TENHO','TEM','TEMOS','TÊM','TINHA','TÍNHAMOS','TINHAM',
  'TIVE','TEVE','TIVEMOS','TIVERAM','TIVESSE','TEREI','TERÁ','TERÍAMOS',
  'TENDO','TIDO',
  // SER
  'SER','SOU','É','SOMOS','SÃO','ERA','ÉRAMOS','ERAM',
  'FUI','FOI','FOMOS','FORAM','FOSSE','SEREI','SERÁ','SERIAMOS',
  'SENDO','SIDO',
  // ESTAR
  'ESTAR','ESTOU','ESTÁ','ESTAMOS','ESTÃO','ESTAVA','ESTÁVAMOS','ESTAVAM',
  'ESTIVE','ESTEVE','ESTIVEMOS','ESTIVERAM','ESTIVESSE','ESTAREI','ESTARÁ',
  'ESTANDO','ESTADO',
  // HAVER
  'HAVER','HÁ','HÃO','HAVIA','HAVÍAMOS','HAVIAM',
  'HOUVE','HOUVEMOS','HOUVERAM','HOUVESSE','HAVERÁ','HAVENDO','HAVIDO',
  // IR
  'IR','VOU','VAI','VAMOS','VÃO','IA','ÍAMOS','IAM',
  'FUI','FOI','FOMOS','FORAM','FOSSE','IREI','IRÁ','INDO',
  // VIR
  'VIR','VENHO','VEM','VIMOS','VÊM','VINHA','VÍNHAMOS','VINHAM',
  'VIM','VEIO','VIEMOS','VIERAM','VIESSE','VIREI','VIRÁ','VINDO','VINDO',
  // QUERER
  'QUERER','QUERO','QUER','QUEREMOS','QUEREM','QUERIA','QUERÍAMOS',
  'QUIS','QUIS','QUISEMOS','QUISERAM','QUISESSE','QUEREI','QUERENDO','QUERIDO',
  // SABER
  'SABER','SEI','SABE','SABEMOS','SABEM','SABIA','SABÍAMOS','SABIAM',
  'SOUBE','SOUBEMOS','SOUBERAM','SOUBESSE','SABEREI','SABENDO','SABIDO',
  // VER
  'VER','VEJO','VÊ','VEMOS','VEEM','VIA','VÍAMOS','VIAM',
  'VI','VIU','VIMOS','VIRAM','VISSE','VEREI','VERÁ','VENDO','VISTO',
  // DAR
  'DAR','DOU','DÁ','DAMOS','DÃO','DAVA','DÁVAMOS','DAVAM',
  'DEI','DEU','DEMOS','DERAM','DESSE','DAREI','DARÁ','DANDO','DADO',
  // FICAR
  'FICAR','FICO','FICA','FICAMOS','FICAM','FICAVA','FICÁVAMOS','FICAVAM',
  'FIQUEI','FICOU','FICAMOS','FICARAM','FICASSE','FICAREI','FICARÁ','FICANDO','FICADO',
  // LEVAR
  'LEVAR','LEVO','LEVA','LEVAMOS','LEVAM','LEVAVA','LEVÁVAMOS','LEVAVAM',
  'LEVEI','LEVOU','LEVAMOS','LEVARAM','LEVASSE','LEVAREI','LEVARÁ','LEVANDO','LEVADO',
  // TRAZER
  'TRAZER','TRAGO','TRAZ','TRAZEMOS','TRAZEM','TRAZIA','TRAZÍAMOS','TRAZIAM',
  'TROUXE','TROUXEMOS','TROUXERAM','TROUXESSE','TRAREI','TRAZENDO','TRAZIDO',
  // COLOCAR
  'COLOCAR','COLOCO','COLOCA','COLOCAMOS','COLOCAM','COLOCAVA','COLOCAVAM',
  'COLOQUEI','COLOCOU','COLOCAMOS','COLOCARAM','COLOCASSE','COLOCAREI','COLOCANDO','COLOCADO',
  // PEGAR
  'PEGAR','PEGO','PEGA','PEGAMOS','PEGAM','PEGAVA','PEGAVAM',
  'PEGUEI','PEGOU','PEGAMOS','PEGARAM','PEGASSE','PEGAREI','PEGANDO','PEGADO',
  // USAR
  'USAR','USO','USA','USAMOS','USAM','USAVA','USAVAM',
  'USEI','USOU','USAMOS','USARAM','USASSE','USAREI','USANDO','USADO',
  // PRECISAR
  'PRECISAR','PRECISO','PRECISA','PRECISAMOS','PRECISAM','PRECISAVA','PRECISAVAM',
  'PRECISEI','PRECISOU','PRECISARAM','PRECISASSE','PRECISAREI','PRECISANDO','PRECISADO',
  // CONSEGUIR
  'CONSEGUIR','CONSIGO','CONSEGUE','CONSEGUIMOS','CONSEGUEM','CONSEGUIA','CONSEGUIAM',
  'CONSEGUI','CONSEGUIU','CONSEGUIMOS','CONSEGUIRAM','CONSEGUISSE','CONSEGUIREI','CONSEGUINDO','CONSEGUIDO',
  // TRABALHAR
  'TRABALHAR','TRABALHO','TRABALHA','TRABALHAMOS','TRABALHAM','TRABALHAVA','TRABALHAVAM',
  'TRABALHEI','TRABALHOU','TRABALHAMOS','TRABALHARAM','TRABALHASSE','TRABALHAREI','TRABALHANDO','TRABALHADO',
  // AJUDAR
  'AJUDAR','AJUDO','AJUDA','AJUDAMOS','AJUDAM','AJUDAVA','AJUDAVAM',
  'AJUDEI','AJUDOU','AJUDAMOS','AJUDARAM','AJUDASSE','AJUDAREI','AJUDANDO','AJUDADO',
  // CONTINUAR
  'CONTINUAR','CONTINUO','CONTINUA','CONTINUAMOS','CONTINUAM','CONTINUAVA','CONTINUAVAM',
  'CONTINUEI','CONTINUOU','CONTINUAMOS','CONTINUARAM','CONTINUASSE','CONTINUAREI','CONTINUANDO','CONTINUADO',
  // TERMINAR
  'TERMINAR','TERMINO','TERMINA','TERMINAMOS','TERMINAM','TERMINAVA','TERMINAVAM',
  'TERMINEI','TERMINOU','TERMINAMOS','TERMINARAM','TERMINASSE','TERMINAREI','TERMINANDO','TERMINADO',
  // COMEÇAR
  'COMEÇAR','COMEÇO','COMEÇA','COMEÇAMOS','COMEÇAM','COMEÇAVA','COMEÇAVAM',
  'COMECEI','COMEÇOU','COMEÇAMOS','COMEÇARAM','COMEÇASSE','COMEÇAREI','COMEÇANDO','COMEÇADO',
  // ENTRAR
  'ENTRAR','ENTRO','ENTRA','ENTRAMOS','ENTRAM','ENTRAVA','ENTRAVAM',
  'ENTREI','ENTROU','ENTRAMOS','ENTRARAM','ENTRASSE','ENTRAREI','ENTRANDO','ENTRADO',
  // SAIR
  'SAIR','SAIO','SAI','SAÍMOS','SAEM','SAÍA','SAÍAMOS','SAÍAM',
  'SAÍ','SAIU','SAÍMOS','SAÍRAM','SAÍSSE','SAIREI','SAINDO','SAÍDO',
  // PASSAR
  'PASSAR','PASSO','PASSA','PASSAMOS','PASSAM','PASSAVA','PASSAVAM',
  'PASSEI','PASSOU','PASSAMOS','PASSARAM','PASSASSE','PASSAREI','PASSANDO','PASSADO',
  // ABRIR
  'ABRIR','ABRO','ABRE','ABRIMOS','ABREM','ABRIA','ABRIAM',
  'ABRI','ABRIU','ABRIMOS','ABRIRAM','ABRISSE','ABRIREI','ABRINDO','ABERTO',
  // FECHAR
  'FECHAR','FECHO','FECHA','FECHAMOS','FECHAM','FECHAVA','FECHAVAM',
  'FECHEI','FECHOU','FECHAMOS','FECHARAM','FECHASSE','FECHAREI','FECHANDO','FECHADO',
  // CHAMAR
  'CHAMAR','CHAMO','CHAMA','CHAMAMOS','CHAMAM','CHAMAVA','CHAMAVAM',
  'CHAMEI','CHAMOU','CHAMAMOS','CHAMARAM','CHAMASSE','CHAMAREI','CHAMANDO','CHAMADO',
  // ENCONTRAR
  'ENCONTRAR','ENCONTRO','ENCONTRA','ENCONTRAMOS','ENCONTRAM','ENCONTRAVA','ENCONTRAVAM',
  'ENCONTREI','ENCONTROU','ENCONTRAMOS','ENCONTRARAM','ENCONTRASSE','ENCONTRAREI','ENCONTRANDO','ENCONTRADO',
  // MOSTRAR
  'MOSTRAR','MOSTRO','MOSTRA','MOSTRAMOS','MOSTRAM','MOSTRAVA','MOSTRAVAM',
  'MOSTREI','MOSTROU','MOSTRAMOS','MOSTRARAM','MOSTRASSE','MOSTRAREI','MOSTRANDO','MOSTRADO',
  // DEIXAR
  'DEIXAR','DEIXO','DEIXA','DEIXAMOS','DEIXAM','DEIXAVA','DEIXAVAM',
  'DEIXEI','DEIXOU','DEIXAMOS','DEIXARAM','DEIXASSE','DEIXAREI','DEIXANDO','DEIXADO',
  // CRIAR
  'CRIAR','CRIO','CRIA','CRIAMOS','CRIAM','CRIAVA','CRIAVAM',
  'CRIEI','CRIOU','CRIAMOS','CRIARAM','CRIASSE','CRIAREI','CRIANDO','CRIADO',
  // FALAR
  'FALAR','FALO','FALA','FALAMOS','FALAM','FALAVA','FALAVAM',
  'FALEI','FALOU','FALAMOS','FALARAM','FALASSE','FALAREI','FALANDO','FALADO',
  // ESCREVER
  'ESCREVER','ESCREVO','ESCREVE','ESCREVEMOS','ESCREVEM','ESCREVIA','ESCREVIAM',
  'ESCREVI','ESCREVEU','ESCREVEMOS','ESCREVERAM','ESCREVESSE','ESCREVEREI','ESCREVENDO','ESCRITO',
  // LER
  'LER','LEIO','LÊ','LEMOS','LEEM','LIA','LÍAMOS','LIAM',
  'LI','LEU','LEMOS','LERAM','LESSE','LEREI','LERÁ','LENDO','LIDO',
  // LIGAR
  'LIGAR','LIGO','LIGA','LIGAMOS','LIGAM','LIGAVA','LIGAVAM',
  'LIGUEI','LIGOU','LIGAMOS','LIGARAM','LIGASSE','LIGAREI','LIGANDO','LIGADO',
  // DESLIGAR
  'DESLIGAR','DESLIGO','DESLIGA','DESLIGAMOS','DESLIGAM','DESLIGAVA','DESLIGAVAM',
  'DESLIGUEI','DESLIGOU','DESLIGARAM','DESLIGASSE','DESLIGAREI','DESLIGANDO','DESLIGADO',
  // ENVIAR
  'ENVIAR','ENVIO','ENVIA','ENVIAMOS','ENVIAM','ENVIAVA','ENVIAVAM',
  'ENVIEI','ENVIOU','ENVIAMOS','ENVIARAM','ENVIASSE','ENVIAREI','ENVIANDO','ENVIADO',
  // RECEBER
  'RECEBER','RECEBO','RECEBE','RECEBEMOS','RECEBEM','RECEBIA','RECEBÍAMOS','RECEBIAM',
  'RECEBI','RECEBEU','RECEBEMOS','RECEBERAM','RECEBESSE','RECEBEREI','RECEBENDO','RECEBIDO',
  // COMPRAR
  'COMPRAR','COMPRO','COMPRA','COMPRAMOS','COMPRAM','COMPRAVA','COMPRAVAM',
  'COMPREI','COMPROU','COMPRAMOS','COMPRARAM','COMPRASSE','COMPRAREI','COMPRANDO','COMPRADO',
  // VENDER
  'VENDER','VENDO','VENDE','VENDEMOS','VENDEM','VENDIA','VENDÍAMOS','VENDIAM',
  'VENDI','VENDEU','VENDEMOS','VENDERAM','VENDESSE','VENDEREI','VENDENDO','VENDIDO',
  // MUDAR
  'MUDAR','MUDO','MUDA','MUDAMOS','MUDAM','MUDAVA','MUDAVAM',
  'MUDEI','MUDOU','MUDAMOS','MUDARAM','MUDASSE','MUDAREI','MUDANDO','MUDADO',
  // MOVER
  'MOVER','MOVO','MOVE','MOVEMOS','MOVEM','MOVIA','MOVÍAMOS','MOVIAM',
  'MOVI','MOVEU','MOVEMOS','MOVERAM','MOVESSE','MOVEREI','MOVENDO','MOVIDO',
  // SUBIR
  'SUBIR','SUBO','SOBE','SUBIMOS','SOBEM','SUBIA','SUBÍAMOS','SUBIAM',
  'SUBI','SUBIU','SUBIMOS','SUBIRAM','SUBISSE','SUBIREI','SUBINDO','SUBIDO',
  // DESCER
  'DESCER','DESÇO','DESCE','DESCEMOS','DESCEM','DESCIA','DESCÍAMOS','DESCIAM',
  'DESCI','DESCEU','DESCEMOS','DESCERAM','DESCESSE','DESCEREI','DESCENDO','DESCIDO',
  // LIMPAR
  'LIMPAR','LIMPO','LIMPA','LIMPAMOS','LIMPAM','LIMPAVA','LIMPAVAM',
  'LIMPEI','LIMPOU','LIMPAMOS','LIMPARAM','LIMPASSE','LIMPAREI','LIMPANDO','LIMPO',
  // CARREGAR
  'CARREGAR','CARREGO','CARREGA','CARREGAMOS','CARREGAM','CARREGAVA','CARREGAVAM',
  'CARREGUEI','CARREGOU','CARREGAMOS','CARREGARAM','CARREGASSE','CARREGAREI','CARREGANDO','CARREGADO',
  // GUARDAR
  'GUARDAR','GUARDO','GUARDA','GUARDAMOS','GUARDAM','GUARDAVA','GUARDAVAM',
  'GUARDEI','GUARDOU','GUARDAMOS','GUARDARAM','GUARDASSE','GUARDAREI','GUARDANDO','GUARDADO',
  // BUSCAR
  'BUSCAR','BUSCO','BUSCA','BUSCAMOS','BUSCAM','BUSCAVA','BUSCAVAM',
  'BUSQUEI','BUSCOU','BUSCAMOS','BUSCARAM','BUSCASSE','BUSCAREI','BUSCANDO','BUSCADO',
  // PROCURAR
  'PROCURAR','PROCURO','PROCURA','PROCURAMOS','PROCURAM','PROCURAVA','PROCURAVAM',
  'PROCUREI','PROCUROU','PROCURAMOS','PROCURARAM','PROCURASSE','PROCURAREI','PROCURANDO','PROCURADO',
  // ATUALIZAR
  'ATUALIZAR','ATUALIZO','ATUALIZA','ATUALIZAMOS','ATUALIZAM','ATUALIZAVA','ATUALIZAVAM',
  'ATUALIZEI','ATUALIZOU','ATUALIZAMOS','ATUALIZARAM','ATUALIZASSE','ATUALIZAREI','ATUALIZANDO','ATUALIZADO',
  // CALCULAR
  'CALCULAR','CALCULO','CALCULA','CALCULAMOS','CALCULAM','CALCULAVA','CALCULAVAM',
  'CALCULEI','CALCULOU','CALCULAMOS','CALCULARAM','CALCULASSE','CALCULAREI','CALCULANDO','CALCULADO',
  // ANALISAR
  'ANALISAR','ANALISO','ANALISA','ANALISAMOS','ANALISAM','ANALISAVA','ANALISAVAM',
  'ANALISEI','ANALISOU','ANALISAMOS','ANALISARAM','ANALISASSE','ANALISAREI','ANALISANDO','ANALISADO',
  // PLANEJAR
  'PLANEJAR','PLANEJO','PLANEJA','PLANEJAMOS','PLANEJAM','PLANEJAVA','PLANEJAVAM',
  'PLANEJEI','PLANEJOU','PLANEJAMOS','PLANEJARAM','PLANEJASSE','PLANEJAREI','PLANEJANDO','PLANEJADO',
  // MELHORAR
  'MELHORAR','MELHORO','MELHORA','MELHORAMOS','MELHORAM','MELHORAVA','MELHORAVAM',
  'MELHOREI','MELHOROU','MELHORAMOS','MELHORARAM','MELHORASSE','MELHORAREI','MELHORANDO','MELHORADO',
  // AUMENTAR
  'AUMENTAR','AUMENTO','AUMENTA','AUMENTAMOS','AUMENTAM','AUMENTAVA','AUMENTAVAM',
  'AUMENTEI','AUMENTOU','AUMENTAMOS','AUMENTARAM','AUMENTASSE','AUMENTAREI','AUMENTANDO','AUMENTADO',
  // REDUZIR
  'REDUZIR','REDUZO','REDUZ','REDUZIMOS','REDUZEM','REDUZIA','REDUZÍAMOS','REDUZIAM',
  'REDUZI','REDUZIU','REDUZIMOS','REDUZIRAM','REDUZISSE','REDUZIREI','REDUZINDO','REDUZIDO',
  // CONTROLAR
  'CONTROLAR','CONTROLO','CONTROLA','CONTROLAMOS','CONTROLAM','CONTROLAVA','CONTROLAVAM',
  'CONTROLEI','CONTROLOU','CONTROLAMOS','CONTROLARAM','CONTROLASSE','CONTROLAREI','CONTROLANDO','CONTROLADO',
  // REGISTRAR
  'REGISTRAR','REGISTRO','REGISTRA','REGISTRAMOS','REGISTRAM','REGISTRAVA','REGISTRAVAM',
  'REGISTREI','REGISTROU','REGISTRAMOS','REGISTRARAM','REGISTRASSE','REGISTRAREI','REGISTRANDO','REGISTRADO',
  // MONITORAR
  'MONITORAR','MONITORO','MONITORA','MONITORAMOS','MONITORAM','MONITORAVA','MONITORAVAM',
  'MONITOREI','MONITOROU','MONITORAMOS','MONITORARAM','MONITORASSE','MONITORAREI','MONITORANDO','MONITORADO',
  // APLICAR
  'APLICAR','APLICO','APLICA','APLICAMOS','APLICAM','APLICAVA','APLICAVAM',
  'APLIQUEI','APLICOU','APLICAMOS','APLICARAM','APLICASSE','APLICAREI','APLICANDO','APLICADO',
  // TESTAR
  'TESTAR','TESTO','TESTA','TESTAMOS','TESTAM','TESTAVA','TESTAVAM',
  'TESTEI','TESTOU','TESTAMOS','TESTARAM','TESTASSE','TESTAREI','TESTANDO','TESTADO',
  // VERIFICAR
  'VERIFICAR','VERIFICO','VERIFICA','VERIFICAMOS','VERIFICAM','VERIFICAVA','VERIFICAVAM',
  'VERIFIQUEI','VERIFICOU','VERIFICAMOS','VERIFICARAM','VERIFICASSE','VERIFICAREI','VERIFICANDO','VERIFICADO',
  // CORRIGIR
  'CORRIGIR','CORRIJO','CORRIGE','CORRIGIMOS','CORRIGEM','CORRIGIA','CORRIGÍAMOS','CORRIGIAM',
  'CORRIGI','CORRIGIU','CORRIGIMOS','CORRIGIRAM','CORRIGISSE','CORRIGIREI','CORRIGINDO','CORRIGIDO',
  // PREPARAR
  'PREPARAR','PREPARO','PREPARA','PREPARAMOS','PREPARAM','PREPARAVA','PREPARAVAM',
  'PREPAREI','PREPAROU','PREPARAMOS','PREPARARAM','PREPARASSE','PREPARAREI','PREPARANDO','PREPARADO',
  // REALIZAR
  'REALIZAR','REALIZO','REALIZA','REALIZAMOS','REALIZAM','REALIZAVA','REALIZAVAM',
  'REALIZEI','REALIZOU','REALIZAMOS','REALIZARAM','REALIZASSE','REALIZAREI','REALIZANDO','REALIZADO',
  // EXECUTAR
  'EXECUTAR','EXECUTO','EXECUTA','EXECUTAMOS','EXECUTAM','EXECUTAVA','EXECUTAVAM',
  'EXECUTEI','EXECUTOU','EXECUTAMOS','EXECUTARAM','EXECUTASSE','EXECUTAREI','EXECUTANDO','EXECUTADO',
  // ELABORAR
  'ELABORAR','ELABORO','ELABORA','ELABORAMOS','ELABORAM','ELABORAVA','ELABORAVAM',
  'ELABOREI','ELABOROU','ELABORAMOS','ELABORARAM','ELABORASSE','ELABORAREI','ELABORANDO','ELABORADO',
  // CONCLUIR
  'CONCLUIR','CONCLUO','CONCLUI','CONCLUÍMOS','CONCLUEM','CONCLUÍA','CONCLUÍAMOS','CONCLUÍAM',
  'CONCLUÍ','CONCLUIU','CONCLUÍMOS','CONCLUÍRAM','CONCLUÍSSE','CONCLUIREI','CONCLUINDO','CONCLUÍDO',
  // DESENVOLVER
  'DESENVOLVER','DESENVOLVO','DESENVOLVE','DESENVOLVEMOS','DESENVOLVEM','DESENVOLVIA','DESENVOLVÍAMOS',
  'DESENVOLVI','DESENVOLVEU','DESENVOLVEMOS','DESENVOLVERAM','DESENVOLVESSE','DESENVOLVEREI','DESENVOLVENDO','DESENVOLVIDO',
  // PESQUISAR
  'PESQUISAR','PESQUISO','PESQUISA','PESQUISAMOS','PESQUISAM','PESQUISAVA','PESQUISAVAM',
  'PESQUISEI','PESQUISOU','PESQUISAMOS','PESQUISARAM','PESQUISASSE','PESQUISAREI','PESQUISANDO','PESQUISADO',
  // COLETAR
  'COLETAR','COLETO','COLETA','COLETAMOS','COLETAM','COLETAVA','COLETAVAM',
  'COLETEI','COLETOU','COLETAMOS','COLETARAM','COLETASSE','COLETAREI','COLETANDO','COLETADO',
  // DOCUMENTAR
  'DOCUMENTAR','DOCUMENTO','DOCUMENTA','DOCUMENTAMOS','DOCUMENTAM','DOCUMENTAVA','DOCUMENTAVAM',
  'DOCUMENTEI','DOCUMENTOU','DOCUMENTAMOS','DOCUMENTARAM','DOCUMENTASSE','DOCUMENTAREI','DOCUMENTANDO','DOCUMENTADO',
  // APRESENTAR
  'APRESENTAR','APRESENTO','APRESENTA','APRESENTAMOS','APRESENTAM','APRESENTAVA','APRESENTAVAM',
  'APRESENTEI','APRESENTOU','APRESENTAMOS','APRESENTARAM','APRESENTASSE','APRESENTAREI','APRESENTANDO','APRESENTADO',
  // ORGANIZAR
  'ORGANIZAR','ORGANIZO','ORGANIZA','ORGANIZAMOS','ORGANIZAM','ORGANIZAVA','ORGANIZAVAM',
  'ORGANIZEI','ORGANIZOU','ORGANIZAMOS','ORGANIZARAM','ORGANIZASSE','ORGANIZAREI','ORGANIZANDO','ORGANIZADO',
  // COLABORAR
  'COLABORAR','COLABORO','COLABORA','COLABORAMOS','COLABORAM','COLABORAVA','COLABORAVAM',
  'COLABOREI','COLABOROU','COLABORAMOS','COLABORARAM','COLABORASSE','COLABORAREI','COLABORANDO','COLABORADO',
  // PARTICIPAR
  'PARTICIPAR','PARTICIPO','PARTICIPA','PARTICIPAMOS','PARTICIPAM','PARTICIPAVA','PARTICIPAVAM',
  'PARTICIPEI','PARTICIPOU','PARTICIPAMOS','PARTICIPARAM','PARTICIPASSE','PARTICIPAREI','PARTICIPANDO','PARTICIPADO',
  // INFORMAR
  'INFORMAR','INFORMO','INFORMA','INFORMAMOS','INFORMAM','INFORMAVA','INFORMAVAM',
  'INFORMEI','INFORMOU','INFORMAMOS','INFORMARAM','INFORMASSE','INFORMAREI','INFORMANDO','INFORMADO',
  // SOLICITAR
  'SOLICITAR','SOLICITO','SOLICITA','SOLICITAMOS','SOLICITAM','SOLICITAVA','SOLICITAVAM',
  'SOLICITEI','SOLICITOU','SOLICITAMOS','SOLICITARAM','SOLICITASSE','SOLICITAREI','SOLICITANDO','SOLICITADO',
  // COMUNICAR
  'COMUNICAR','COMUNICO','COMUNICA','COMUNICAMOS','COMUNICAM','COMUNICAVA','COMUNICAVAM',
  'COMUNIQUEI','COMUNICOU','COMUNICAMOS','COMUNICARAM','COMUNICASSE','COMUNICAREI','COMUNICANDO','COMUNICADO',
  // ACOMPANHAR
  'ACOMPANHAR','ACOMPANHO','ACOMPANHA','ACOMPANHAMOS','ACOMPANHAM','ACOMPANHAVA','ACOMPANHAVAM',
  'ACOMPANHEI','ACOMPANHOU','ACOMPANHAMOS','ACOMPANHARAM','ACOMPANHASSE','ACOMPANHAREI','ACOMPANHANDO','ACOMPANHADO',
  // SUPERVISIONAR
  'SUPERVISIONAR','SUPERVISIONO','SUPERVISIONA','SUPERVISIONAMOS','SUPERVISIONAM',
  'SUPERVISIONAVA','SUPERVISIONAVAM','SUPERVISIONEI','SUPERVISIONOU','SUPERVISIONANDO','SUPERVISIONADO',
  // ORIENTAR
  'ORIENTAR','ORIENTO','ORIENTA','ORIENTAMOS','ORIENTAM','ORIENTAVA','ORIENTAVAM',
  'ORIENTEI','ORIENTOU','ORIENTAMOS','ORIENTARAM','ORIENTASSE','ORIENTAREI','ORIENTANDO','ORIENTADO',
  // CAPACITAR
  'CAPACITAR','CAPACITO','CAPACITA','CAPACITAMOS','CAPACITAM','CAPACITAVA','CAPACITAVAM',
  'CAPACITEI','CAPACITOU','CAPACITAMOS','CAPACITARAM','CAPACITASSE','CAPACITAREI','CAPACITANDO','CAPACITADO',
  // TREINAR
  'TREINAR','TREINO','TREINA','TREINAMOS','TREINAM','TREINAVA','TREINAVAM',
  'TREINEI','TREINOU','TREINAMOS','TREINARAM','TREINASSE','TREINAREI','TREINANDO','TREINADO',
  // AVALIAR
  'AVALIAR','AVALIO','AVALIA','AVALIAMOS','AVALIAM','AVALIAVA','AVALIAVAM',
  'AVALIEI','AVALIOU','AVALIAMOS','AVALIARAM','AVALIASSE','AVALIAREI','AVALIANDO','AVALIADO',
  // REVISAR
  'REVISAR','REVISO','REVISA','REVISAMOS','REVISAM','REVISAVA','REVISAVAM',
  'REVISEI','REVISOU','REVISAMOS','REVISARAM','REVISASSE','REVISAREI','REVISANDO','REVISADO',
  // APROVAR
  'APROVAR','APROVO','APROVA','APROVAMOS','APROVAM','APROVAVA','APROVAVAM',
  'APROVEI','APROVOU','APROVAMOS','APROVARAM','APROVASSE','APROVAREI','APROVANDO','APROVADO',
  // ARQUIVAR
  'ARQUIVAR','ARQUIVO','ARQUIVA','ARQUIVAMOS','ARQUIVAM','ARQUIVAVA','ARQUIVAVAM',
  'ARQUIVEI','ARQUIVOU','ARQUIVAMOS','ARQUIVARAM','ARQUIVASSE','ARQUIVAREI','ARQUIVANDO','ARQUIVADO',
  // CADASTRAR
  'CADASTRAR','CADASTRO','CADASTRA','CADASTRAMOS','CADASTRAM','CADASTRAVA','CADASTRAVAM',
  'CADASTREI','CADASTROU','CADASTRAMOS','CADASTRARAM','CADASTRASSE','CADASTRAREI','CADASTRANDO','CADASTRADO',
  // INSTALAR
  'INSTALAR','INSTALO','INSTALA','INSTALAMOS','INSTALAM','INSTALAVA','INSTALAVAM',
  'INSTALEI','INSTALOU','INSTALAMOS','INSTALARAM','INSTALASSE','INSTALAREI','INSTALANDO','INSTALADO',
  // CONFIGURAR
  'CONFIGURAR','CONFIGURO','CONFIGURA','CONFIGURAMOS','CONFIGURAM','CONFIGURAVA','CONFIGURAVAM',
  'CONFIGUREI','CONFIGUROU','CONFIGURAMOS','CONFIGURARAM','CONFIGURASSE','CONFIGURAREI','CONFIGURANDO','CONFIGURADO',
  // MANTER
  'MANTER','MANTENHO','MANTÉM','MANTEMOS','MANTÊM','MANTINHA','MANTÍNHAMOS','MANTINHAM',
  'MANTIVE','MANTEVE','MANTIVEMOS','MANTIVERAM','MANTIVESSE','MANTEREI','MANTENDO','MANTIDO',
  // SEPARAR
  'SEPARAR','SEPARO','SEPARA','SEPARAMOS','SEPARAM','SEPARAVA','SEPARAVAM',
  'SEPAREI','SEPAROU','SEPARAMOS','SEPARARAM','SEPARASSE','SEPARAREI','SEPARANDO','SEPARADO',
  // HIGIENIZAR
  'HIGIENIZAR','HIGIENIZO','HIGIENIZA','HIGIENIZAMOS','HIGIENIZAM','HIGIENIZAVA','HIGIENIZAVAM',
  'HIGIENIZEI','HIGIENIZOU','HIGIENIZAMOS','HIGIENIZARAM','HIGIENIZASSE','HIGIENIZAREI','HIGIENIZANDO','HIGIENIZADO',
  // ENTREGAR
  'ENTREGAR','ENTREGO','ENTREGA','ENTREGAMOS','ENTREGAM','ENTREGAVA','ENTREGAVAM',
  'ENTREGUEI','ENTREGOU','ENTREGAMOS','ENTREGARAM','ENTREGASSE','ENTREGAREI','ENTREGANDO','ENTREGUE',
  // ENCAMINHAR
  'ENCAMINHAR','ENCAMINHO','ENCAMINHA','ENCAMINHAMOS','ENCAMINHAM','ENCAMINHAVA','ENCAMINHAVAM',
  'ENCAMINHEI','ENCAMINHOU','ENCAMINHAMOS','ENCAMINHARAM','ENCAMINHASSE','ENCAMINHAREI','ENCAMINHANDO','ENCAMINHADO',
  // DIGITALIZAR
  'DIGITALIZAR','DIGITALIZO','DIGITALIZA','DIGITALIZAMOS','DIGITALIZAM','DIGITALIZAVA','DIGITALIZAVAM',
  'DIGITALIZEI','DIGITALIZOU','DIGITALIZAMOS','DIGITALIZARAM','DIGITALIZASSE','DIGITALIZAREI','DIGITALIZANDO','DIGITALIZADO',
  // ATENDER
  'ATENDER','ATENDO','ATENDE','ATENDEMOS','ATENDEM','ATENDIA','ATENDÍAMOS','ATENDIAM',
  'ATENDI','ATENDEU','ATENDEMOS','ATENDERAM','ATENDESSE','ATENDEREI','ATENDENDO','ATENDIDO',
  // RECEBER
  'RECEBER','RECEBO','RECEBE','RECEBEMOS','RECEBEM','RECEBIA','RECEBÍAMOS','RECEBIAM',
  'RECEBI','RECEBEU','RECEBEMOS','RECEBERAM','RECEBESSE','RECEBEREI','RECEBENDO','RECEBIDO',
  // TRANSFERIR
  'TRANSFERIR','TRANSFIRO','TRANSFERE','TRANSFERIMOS','TRANSFEREM','TRANSFERIA','TRANSFERIAM',
  'TRANSFERI','TRANSFERIU','TRANSFERIMOS','TRANSFERIRAM','TRANSFERISSE','TRANSFERIREI','TRANSFERINDO','TRANSFERIDO',
  // IMPRIMIR
  'IMPRIMIR','IMPRIMO','IMPRIME','IMPRIMIMOS','IMPRIMEM','IMPRIMIA','IMPRIMÍAMOS','IMPRIMIAM',
  'IMPRIMI','IMPRIMIU','IMPRIMIMOS','IMPRIMIRAM','IMPRIMISSE','IMPRIMIREI','IMPRIMINDO','IMPRESSO',
  // PREENCHER
  'PREENCHER','PREENCHO','PREENCHE','PREENCHEMOS','PREENCHEM','PREENCHIA','PREENCHÍAMOS','PREENCHIAM',
  'PREENCHI','PREENCHEU','PREENCHEMOS','PREENCHERAM','PREENCHESSE','PREENCHEREI','PREENCHENDO','PREENCHIDO',
  // FECHAR
  'FECHAR','FECHO','FECHA','FECHAMOS','FECHAM','FECHAVA','FECHAVAM',
  'FECHEI','FECHOU','FECHAMOS','FECHARAM','FECHASSE','FECHAREI','FECHANDO','FECHADO',
  // DISTRIBUIR
  'DISTRIBUIR','DISTRIBUO','DISTRIBUI','DISTRIBUÍMOS','DISTRIBUEM','DISTRIBUÍA','DISTRIBUÍAMOS',
  'DISTRIBUÍ','DISTRIBUIU','DISTRIBUÍMOS','DISTRIBUÍRAM','DISTRIBUÍSSE','DISTRIBUIREI','DISTRIBUINDO','DISTRIBUÍDO',

  // ── Substantivos gerais ampliados ─────────────────────────────
  'ATIVIDADE','ATIVIDADES','TAREFA','TAREFAS','FUNÇÃO','FUNÇÕES','CARGO','CARGOS',
  'SERVIÇO','SERVIÇOS','TRABALHO','TRABALHOS','OPERAÇÃO','OPERAÇÕES','PROCEDIMENTO','PROCEDIMENTOS',
  'PROCESSO','PROCESSOS','ETAPA','ETAPAS','FASE','FASES','PASSO','PASSOS',
  'INSTRUÇÃO','INSTRUÇÕES','PROTOCOLO','PROTOCOLOS','MANUAL','MANUAIS',
  'ROTINA','ROTINAS','CRONOGRAMA','CRONOGRAMAS','PRAZO','PRAZOS','META','METAS',
  'OBJETIVO','OBJETIVOS','RESULTADO','RESULTADOS','PRODUTO','PRODUTOS','SAÍDA','SAÍDAS',
  'ENTRADA','ENTRADAS','DADO','DADOS','INFORMAÇÃO','INFORMAÇÕES','RELATÓRIO','RELATÓRIOS',
  'DOCUMENTO','DOCUMENTOS','ARQUIVO','ARQUIVOS','PASTA','PASTAS','FICHA','FICHAS',
  'FORMULÁRIO','FORMULÁRIOS','PLANILHA','PLANILHAS','TABELA','TABELAS','LISTA','LISTAS',
  'ÍNDICE','ÍNDICES','REGISTRO','REGISTROS','PROTOCOLO','PROTOCOLOS',
  'CONTRATO','CONTRATOS','ACORDO','ACORDOS','PARCERIA','PARCERIAS',
  'PROJETO','PROJETOS','PLANO','PLANOS','PROGRAMA','PROGRAMAS','AÇÃO','AÇÕES',
  'ESTRATÉGIA','ESTRATÉGIAS','POLÍTICA','POLÍTICAS','NORMA','NORMAS','REGRA','REGRAS',
  'CRITÉRIO','CRITÉRIOS','INDICADOR','INDICADORES','MÉTRICA','MÉTRICAS',
  'DIAGNÓSTICO','DIAGNÓSTICOS','ANÁLISE','ANÁLISES','AVALIAÇÃO','AVALIAÇÕES',
  'RELATORIA','AUDITORIA','AUDITORIAS','FISCALIZAÇÃO','FISCALIZAÇÕES',
  'VISTORIA','VISTORIAS','INSPEÇÃO','INSPEÇÕES','REVISÃO','REVISÕES',
  'CORREÇÃO','CORREÇÕES','AJUSTE','AJUSTES','MELHORIA','MELHORIAS',
  'IMPLANTAÇÃO','IMPLEMENTAÇÃO','DESENVOLVIMENTO','DESENVOLVIMENTOS',
  'ELABORAÇÃO','ELABORAÇÕES','EXECUÇÃO','EXECUÇÕES','REALIZAÇÃO','REALIZAÇÕES',
  'CONCLUSÃO','CONCLUSÕES','FINALIZAÇÃO','FINALIZAÇÕES','ENTREGA','ENTREGAS',
  'APROVAÇÃO','APROVAÇÕES','VALIDAÇÃO','VALIDAÇÕES','TESTE','TESTES',
  'VERIFICAÇÃO','VERIFICAÇÕES','CONFERÊNCIA','CONFERÊNCIAS',
  'COMUNICAÇÃO','COMUNICAÇÕES','REUNIÃO','REUNIÕES','ENCONTRO','ENCONTROS',
  'TREINAMENTO','TREINAMENTOS','CAPACITAÇÃO','CAPACITAÇÕES','ORIENTAÇÃO','ORIENTAÇÕES',
  'APRESENTAÇÃO','APRESENTAÇÕES','PALESTRA','PALESTRAS','CURSO','CURSOS',
  'EVENTO','EVENTOS','ATIVIDADE','ATIVIDADES','EXERCÍCIO','EXERCÍCIOS',
  'PRÁTICA','PRÁTICAS','ESTUDO','ESTUDOS','PESQUISA','PESQUISAS',
  'EXPERIMENTO','EXPERIMENTOS','ENSAIO','ENSAIOS','TESTE','TESTES',
  'MEDIÇÃO','MEDIÇÕES','ANÁLISE','ANÁLISES','AMOSTRA','AMOSTRAS',
  'COLETA','COLETAS','EXTRAÇÃO','EXTRAÇÕES','FILTRAÇÃO','FILTRAÇÕES',
  'PREPARAÇÃO','PREPARAÇÕES','MONTAGEM','MONTAGENS','INSTALAÇÃO','INSTALAÇÕES',
  'MANUTENÇÃO','MANUTENÇÕES','REPARO','REPAROS','CONSERTO','CONSERTOS',
  'LIMPEZA','LIMPEZAS','HIGIENIZAÇÃO','HIGIENIZAÇÕES','DESINFECÇÃO','DESINFECÇÕES',
  'ESTERILIZAÇÃO','ESTERILIZAÇÕES','DESCARTE','DESCARTES',
  'ORGANIZAÇÃO','ORGANIZAÇÕES','CATALOGAÇÃO','CATALOGAÇÕES','CLASSIFICAÇÃO','CLASSIFICAÇÕES',
  'SEPARAÇÃO','SEPARAÇÕES','SELEÇÃO','SELEÇÕES','TRIAGEM','TRIAGENS',
  'ARMAZENAMENTO','ARMAZENAMENTOS','ESTOQUE','ESTOQUES','INVENTÁRIO','INVENTÁRIOS',
  'SUPRIMENTO','SUPRIMENTOS','REQUISIÇÃO','REQUISIÇÕES','SOLICITAÇÃO','SOLICITAÇÕES',
  'PEDIDO','PEDIDOS','COMPRA','COMPRAS','FORNECIMENTO','FORNECIMENTOS',
  'ENTREGA','ENTREGAS','RECEBIMENTO','RECEBIMENTOS','ENVIO','ENVIOS',
  'TRANSPORTE','TRANSPORTES','DISTRIBUIÇÃO','DISTRIBUIÇÕES','LOGÍSTICA',
  'CONTROLE','CONTROLES','ACOMPANHAMENTO','ACOMPANHAMENTOS','MONITORAMENTO','MONITORAMENTOS',

  // ── Ciências biológicas e saúde ───────────────────────────────
  'BIOLOGIA','BIOLÓGICO','BIOLÓGICA','BIOLÓGICOS','BIOLÓGICAS',
  'BIOQUÍMICA','BIOFÍSICA','BIOMOLECULAR','BIOTECNOLOGIA',
  'CÉLULA','CÉLULAS','CELULAR','CELULARES',
  'TECIDO','TECIDOS','ÓRGÃO','ÓRGÃOS','SISTEMA','SISTEMAS',
  'PROTEÍNA','PROTEÍNAS','CARBOIDRATO','CARBOIDRATOS','LIPÍDIO','LIPÍDIOS',
  'ÁCIDO','ÁCIDOS','BASE','BASES','SAL','SAIS',
  'ENZIMA','ENZIMAS','HORMÔNIO','HORMÔNIOS','VITAMINA','VITAMINAS',
  'MINERAL','MINERAIS','NUTRIENTE','NUTRIENTES','MACRONUTRIENTE','MICRONUTRIENTE',
  'NITROGÊNIO','FÓSFORO','POTÁSSIO','CÁLCIO','MAGNÉSIO','ENXOFRE',
  'FERRO','ZINCO','MANGANÊS','COBRE','BORO','MOLIBDÊNIO',
  'METABOLISMO','METABOLISMO','METABOLITA','METABOLITAS',
  'FOTOSSÍNTESE','RESPIRAÇÃO','TRANSPIRAÇÃO','ABSORÇÃO',
  'GERMINAÇÃO','BROTAÇÃO','FLORESCIMENTO','FRUTIFICAÇÃO','SENESCÊNCIA',
  'CRESCIMENTO','DESENVOLVIMENTO','MATURAÇÃO','AMADURECIMENTO',
  'DORMÊNCIA','VIABILIDADE','VIGOR','GERMINABILIDADE',
  'MICROBIOLOGIA','MICROBIANO','MICROBIANA','MICROBIOTAS',
  'BACTÉRIA','BACTÉRIAS','BACTERIANO','BACTERIANA',
  'VÍRUS','VIRAL','VIRAIS','VIRULÊNCIA','PATOGENICIDADE',
  'FUNGO','FUNGOS','FÚNGICO','FÚNGICA','MICELIAL','MICÉLIO',
  'PROTOZOÁRIO','PROTOZOÁRIOS','HELMINTO','HELMINTOS','NEMATOIDE','NEMATOIDES',
  'PARASITA','PARASITAS','PARASITISMO','SIMBIOSE','MUTUALISMO',
  'HOSPEDEIRO','HOSPEDEIROS','VETOR','VETORES','INOCULO','INÓCULO',
  'INFEÇÃO','INFECÇÃO','INFECÇÕES','COLONIZAÇÃO','COLONIZAR',
  'PATÓGENO','PATÓGENOS','PATOGÊNICO','PATOGÊNICA',
  'DOENÇA','DOENÇAS','SINTOMA','SINTOMAS','SINAL','SINAIS',
  'DIAGNOSE','DIAGNÓSTICO','DIAGNÓSTICOS',
  'RESISTÊNCIA','TOLERÂNCIA','SUSCETIBILIDADE','SUSCEPTIBILIDADE',
  'IMUNIDADE','IMUNE','ANTICORPO','ANTICORPOS','ANTÍGENO','ANTÍGENOS',
  'VACINA','VACINAS','VACINAÇÃO','SORO','SOROS','SOROTIPO','SOROTIPOS',

  // ── Química e física ──────────────────────────────────────────
  'QUÍMICA','QUÍMICO','QUÍMICA','REAÇÃO','REAÇÕES','REATIVO','REATIVOS',
  'MOLÉCULA','MOLÉCULAS','ÁTOMO','ÁTOMOS','ÍON','ÍONS','RADICAL','RADICAIS',
  'COMPOSTO','COMPOSTOS','ELEMENTO','ELEMENTOS','MISTURA','MISTURAS',
  'SOLUÇÃO','SOLUÇÕES','SUSPENSÃO','SUSPENSÕES','EMULSÃO','EMULSÕES',
  'CONCENTRAÇÃO','CONCENTRAÇÕES','DILUIÇÃO','DILUIÇÕES','DISSOLUÇÃO',
  'PH','ACIDEZ','BASICIDADE','ALCALINIDADE','NEUTRALIZAÇÃO','NEUTRALIZAR',
  'OXIDAÇÃO','REDUÇÃO','CATÁLISE','CATALISADOR','CATALISADORES',
  'PRECIPITAÇÃO','PRECIPITADO','SEDIMENTAÇÃO','SEDIMENTO',
  'DESTILAÇÃO','DESTILAR','CRISTALIZAÇÃO','CRISTALIZAR',
  'CENTRIFUGAÇÃO','CENTRIFUGAR','DECANTAÇÃO','DECANTAR',
  'TITULAÇÃO','TITULAR','INDICADOR','INDICADORES',
  'ESPECTROSCOPIA','ESPECTROFOTOMETRIA','CROMATOGRAFIA','ELETROFORESE',
  'ABSORBÂNCIA','TRANSMITÂNCIA','FLUORESCÊNCIA','LUMINESCÊNCIA',
  'DENSIDADE','VISCOSIDADE','TENSÃO','PRESSÃO','TEMPERATURA','UMIDADE',
  'MASSA','VOLUME','COMPRIMENTO','LARGURA','ALTURA','ÁREA','PROFUNDIDADE',
  'VELOCIDADE','ACELERAÇÃO','FORÇA','ENERGIA','POTÊNCIA','TRABALHO',
  'CALOR','ENTROPIA','ENTALPIA','GIBBS','EQUILÍBRIO',
  'ELETRICIDADE','CORRENTE','TENSÃO','RESISTÊNCIA','CAPACITÂNCIA',
  'MAGNÉTICO','MAGNÉTICA','CAMPO','FLUXO',

  // ── Unidades de medida ────────────────────────────────────────
  'METRO','METROS','CENTÍMETRO','CENTÍMETROS','MILÍMETRO','MILÍMETROS',
  'QUILÔMETRO','QUILÔMETROS','HECTARE','HECTARES','ALQUEIRE','ALQUEIRES',
  'GRAMA','GRAMAS','QUILOGRAMA','QUILOGRAMAS','MILIGRAMA','MILIGRAMAS',
  'TONELADA','TONELADAS','ARROBA','ARROBAS','SACO','SACOS',
  'LITRO','LITROS','MILILITRO','MILILITROS','MICROLITRO','MICROLITROS',
  'HORA','HORAS','MINUTO','MINUTOS','SEGUNDO','SEGUNDOS','DIA','DIAS',
  'SEMANA','SEMANAS','MÊS','MESES','ANO','ANOS',
  'PORCENTAGEM','PERCENTUAL','FRAÇÃO','FRAÇÕES','PROPORÇÃO','PROPORÇÕES',
  'CONCENTRAÇÃO','PPM','PPB','MOL','MOLAR','OSMOL',
  'CELSIUS','FAHRENHEIT','KELVIN','GRAU','GRAUS',
  'PASCAL','BAR','ATM','MMHG','ATIMOSFERA',
  'WATT','JOULE','CALORIA','QUILOCALORIA','KCAL',
  'AMPERE','VOLT','OHM','FARAD','HERTZ',

  // ── Agronegócio e gestão rural ────────────────────────────────
  'AGRONEGÓCIO','AGROPECUÁRIA','AGROPECUÁRIO','AGROPECUÁRIA',
  'PRODUTOR','PRODUTORES','PROPRIEDADE','PROPRIEDADES','FAZENDA','FAZENDAS',
  'SÍTIO','SÍTIOS','CHÁCARA','CHÁCARAS','ASSENTAMENTO','ASSENTAMENTOS',
  'COOPERATIVA','COOPERATIVAS','ASSOCIAÇÃO','ASSOCIAÇÕES','SINDICATO','SINDICATOS',
  'EMBRAPA','SENAR','MAPA','SEMA','ANA','IBAMA',
  'BPA','GAP','BOAS PRÁTICAS','RASTREABILIDADE',
  'CERTIFICAÇÃO','CERTIFICAR','ORGÂNICO','ORGÂNICOS','ORGÂNICA','ORGÂNICAS',
  'CONVENCIONAL','INTEGRADO','SUSTENTÁVEL','SUSTENTÁVEIS',
  'PRODUÇÃO INTEGRADA','MANEJO INTEGRADO','AGRICULTURA FAMILIAR',
  'IRRIGAÇÃO','DRENAGEM','FERTIRRIGAÇÃO','MICROIRRIGAÇÃO','GOTEJAMENTO',
  'PIVÔ','ASPERSÃO','SULCO','INUNDAÇÃO','SUPERFICIAL',
  'SOLO','SOLOS','PERFIL','HORIZONTE','CAMADA','TEXTURA',
  'ARGILOSO','ARENOSO','SILTOSO','FRANCO','AREIA','ARGILA','SILTE',
  'MATÉRIA ORGÂNICA','HÚMUS','COMPOSTO','COMPOSTOS','COMPOSTAGEM',
  'ADUBAÇÃO VERDE','ROTAÇÃO','CONSÓRCIO','SUCESSÃO',
  'EROSÃO','ERODIBILIDADE','CURVA DE NÍVEL','TERRAÇO','TERRACEAMENTO',
  'CONSERVAÇÃO DO SOLO','PLANTIO DIRETO','CULTIVO MÍNIMO',
  'COBERTURA','COBERTURA MORTA','PALHADA','MULCHING',
  'SAFRINHA','ENTRESSAFRA','SAFRA','COLHEITA','PÓS-COLHEITA',
  'BENEFICIAMENTO','PROCESSAMENTO','ARMAZENAGEM','SECAGEM','SECO',
  'SECADOR','SILOS','SILO','GRANELEIRO','ARMAZÉM','ARMAZÉNS',
  'UMIDADE DE GRÃO','QUEBRA','PERDAS','DESCONTO','CLASSIFICAÇÃO',
  'TIPO','TIPOS','PENEIRA','PENEIRAS','IMPUREZA','IMPUREZAS',
  'VARIEDADE','VARIEDADES','HÍBRIDO','HÍBRIDOS','LINHAGEM','LINHAGENS',
  'CULTIVAR','CULTIVARES','SELEÇÃO','MELHORAMENTO','GENÉTICA','GENÉTICO',
  'FITOTECNIA','FITOMELHORAMENTO','BIOTECNOLOGIA VEGETAL',
  'FENOLOGIA','FENOLÓGICO','ESTÁDIO','ESTÁDIOS','FASE VEGETATIVA','FASE REPRODUTIVA',
  'EMERGÊNCIA','FLORESCIMENTO','ENCHIMENTO DE GRÃOS','MATURAÇÃO FISIOLÓGICA',
  'PONTO DE COLHEITA','ÍNDICE DE MATURIDADE',
  'RENDIMENTO','PRODUTIVIDADE','PRODUÇÃO','TONELADA POR HECTARE',
  'CUSTO','RECEITA','LUCRO','MARGEM','RETORNO','INVESTIMENTO',

  // ── Fitopatologia e entomologia avançada ──────────────────────
  'MURCHAMENTO','AMARELECIMENTO','CLOROSE','NECROSE','MANCHAS',
  'LESÃO','LESÕES','PÚSTULA','PÚSTULAS','ESPORULAÇÃO','ESPORO','ESPOROS',
  'CANCRO','PODRIDÃO','APODRECIMENTO','MUMIFICAÇÃO',
  'TOMBAMENTO','DAMPING-OFF','RIZOCTONIOSE','FUSARIOSE','PYTHIUM',
  'FERRUGEM','OÍDIO','MÍLDIO','ANTRACNOSE','CERCOSPORIOSE',
  'VERRUGOSE','GOMOSE','EXSUDAÇÃO','EXSUDADO',
  'VÍRUS DO MOSAICO','BEGOMOVÍRUS','TOSPOVÍRUS','CRINIVÍRUS',
  'NEMATOIDE DE GALHA','NEMATOIDE DE CISTO','NEMATOIDE RENIFORME',
  'MELOIDOGYNE','HETERODERA','PRATYLENCHUS','ROTYLENCHULUS',
  'AFÍDEO','PULGÃO','MOSCA BRANCA','TRIPES','ÁCARO RAJADO',
  'LAGARTA','BROCA','PERCEVEJO','CIGARRINHA','COCHONILHA',
  'BESOUROS','BESOURO','VAQUINHA','DIABRÓTICA','SPODOPTERA',
  'HELICOVERPA','ANTICARSIA','BEMISIA','FRANKLINIELLA',
  'TETRANYCHUS','BREVIPALPUS',
  'ARMADILHA','ARMADILHAS','FEROMÔNIO','FEROMÔNIOS','ATRATIVO','ATRATIVOS',
  'MONITORAMENTO DE PRAGAS','LIMIAR DE AÇÃO','NÍVEL DE CONTROLE',
  'INSETICIDA BIOLÓGICO','FUNGICIDA BIOLÓGICO','BIOPESTICIDA',
  'BACILLUS','BEAUVERIA','METARHIZIUM','TRICHODERMA',

  // ── Meio ambiente avançado ────────────────────────────────────
  'ECOSSISTEMA','ECOSSISTEMAS','BIOMA','BIOMAS','HABITATS','HABITAT',
  'BIODIVERSIDADE','DIVERSIDADE','ESPÉCIE','ESPÉCIES','ENDÊMICO','ENDÊMICA',
  'NATIVO','NATIVA','EXÓTICO','EXÓTICA','INVASOR','INVASORA',
  'FLORESTA','FLORESTAS','FLORESTAL','REFLORESTAMENTO','PLANTAÇÃO FLORESTAL',
  'CERRADO','CAATINGA','PANTANAL','AMAZÔNIA','MATA ATLÂNTICA',
  'MATA CILIAR','APP','ÁREA DE PRESERVAÇÃO PERMANENTE','RESERVA LEGAL',
  'CORREDOR ECOLÓGICO','ZONA DE AMORTECIMENTO','UC','UNIDADE DE CONSERVAÇÃO',
  'IMPACTO AMBIENTAL','PASSIVO AMBIENTAL','LICENÇA AMBIENTAL','EIA','RIMA',
  'EMISSÃO','EMISSÕES','GASES','GEE','CO2','METANO','CARBONO',
  'PEGADA DE CARBONO','SEQUESTRO DE CARBONO','NEUTRALIZAÇÃO',
  'EFLUENTE','EFLUENTES','TRATAMENTO DE EFLUENTES','ETE','ETA',
  'RESÍDUO SÓLIDO','ATERRO','COMPOSTAGEM','RECICLAGEM','REÚSO',
  'ÁGUA','RECURSO HÍDRICO','AQUÍFERO','BACIA HIDROGRÁFICA','NASCENTE',
  'RIBEIRÃO','CÓRREGO','LAGO','LAGOA','REPRESA','RESERVATÓRIO',
  'OUTORGA','CAPTAÇÃO','CONSUMO','DESPERDÍCIO','ECONOMIA',
  'ENERGIA SOLAR','ENERGIA EÓLICA','BIOMASSA','BIOGÁS','BIOCOMBUSTÍVEL',
  'SUSTENTABILIDADE','DESENVOLVIMENTO SUSTENTÁVEL','AGENDA','ODS',

  // ── Educação e academia ───────────────────────────────────────
  'EDUCAÇÃO','ENSINO','APRENDIZAGEM','APRENDIZADO','CONHECIMENTO',
  'COMPETÊNCIA','COMPETÊNCIAS','HABILIDADE','HABILIDADES','ATITUDE','ATITUDES',
  'CURRÍCULO','CURRICULAR','EMENTA','EMENTAS','CONTEÚDO','CONTEÚDOS',
  'AULA','AULAS','PRÁTICA','PRÁTICAS','TEÓRICA','TEÓRICAS','TEÓRICO','TEÓRICOS',
  'LABORATÓRIO','LABORATÓRIOS','CAMPO','CAMPOS','ESTÁGIO','ESTÁGIOS',
  'RELATÓRIO DE ESTÁGIO','RELATÓRIO FINAL','MONOGRAFIA','TCC',
  'DISSERTAÇÃO','TESE','ARTIGO','ARTIGOS','PUBLICAÇÃO','PUBLICAÇÕES',
  'PESQUISA','PESQUISAS','PROJETO DE PESQUISA','INICIAÇÃO CIENTÍFICA',
  'BOLSA','BOLSAS','FAPESP','CNPQ','CAPES','FINEP',
  'PROFESSOR','PROFESSORES','ORIENTADOR','ORIENTADORES','COORDENADOR','COORDENADORES',
  'ALUNO','ALUNOS','ESTUDANTE','ESTUDANTES','DISCENTE','DISCENTES',
  'ESTAGIÁRIO','ESTAGIÁRIOS','TRAINEE','RESIDÊNCIA',
  'GRADUAÇÃO','PÓS-GRADUAÇÃO','ESPECIALIZAÇÃO','MESTRADO','DOUTORADO',
  'BACHARELADO','LICENCIATURA','TECNÓLOGO','TÉCNICO',
  'SEMESTRE','SEMESTRES','PERÍODO','PERÍODOS','ANO LETIVO',
  'DISCIPLINA','DISCIPLINAS','CRÉDITO','CRÉDITOS','CARGA HORÁRIA',
  'NOTA','NOTAS','FREQUÊNCIA','FREQUÊNCIAS','AVALIAÇÃO','AVALIAÇÕES',
  'PROVA','PROVAS','EXAME','EXAMES','TRABALHO','TRABALHOS',
  'DEFESA','DEFESAS','BANCA','BANCAS','PARECER','PARECERES',
  'MATRÍCULA','MATRÍCULAS','INSCRIÇÃO','INSCRIÇÕES','CANCELAMENTO',
  'TRANCAMENTO','APROVAÇÃO','REPROVAÇÃO','RECUPERAÇÃO',
  'BIBLIOTECA','BIBLIOTECAS','ACERVO','PERIÓDICO','PERIÓDICOS',
  'BASES DE DADOS','BASE DE DADOS','PORTAL','REPOSITÓRIO',

  // ── Administração e gestão ────────────────────────────────────
  'ADMINISTRAÇÃO','GESTÃO','GERENCIAMENTO','GERENCIAMENTO',
  'PLANEJAMENTO','ORGANIZAÇÃO','DIREÇÃO','CONTROLE',
  'EFICIÊNCIA','EFICÁCIA','EFETIVIDADE','PRODUTIVIDADE','QUALIDADE',
  'PROCESSO','PROCESSOS','FLUXO','FLUXOS','MAPEAMENTO','MAPEAMENTOS',
  'ISO','QUALIDADE TOTAL','TQM','PDCA','PLANEJAR','EXECUTAR','CHECAR','AGIR',
  'KAIZEN','LEAN','SCRUM','AGILE','KANBAN',
  'INDICADOR','INDICADORES','KPI','DASHBOARD','SCORECARD',
  'REUNIÃO','REUNIÕES','PAUTA','PAUTAS','ATA','ATAS','DELIBERAÇÃO',
  'TOMADA DE DECISÃO','DECISÃO','DECISÕES','DIRETRIZ','DIRETRIZES',
  'ORÇAMENTO','ORÇAMENTOS','BUDGET','FORECAST','PLANEJAMENTO FINANCEIRO',
  'RECEITA','DESPESA','CUSTO','MARGEM','LUCRO','PREJUÍZO','RESULTADO',
  'CONTABILIDADE','FISCAL','TRIBUTÁRIO','TRIBUTÁRIA','NOTA FISCAL',
  'BALANCETE','BALANÇO','DRE','FLUXO DE CAIXA',
  'CONTRATO','CONTRATOS','LICITAÇÃO','LICITAÇÕES','EDITAL','EDITAIS',
  'PROPOSTA','PROPOSTAS','CONCORRÊNCIA','PREGÃO','TOMADA DE PREÇO',
  'FORNECEDOR','FORNECEDORES','PARCEIRO','PARCEIROS','CLIENTE','CLIENTES',
  'SLA','ACORDO DE NÍVEL','PRAZO','PRAZOS','ENTREGÁVEL','ENTREGÁVEIS',
  'RISCO','RISCOS','MITIGAÇÃO','CONTINGÊNCIA','PLANO B',
  'COMUNICAÇÃO','COMUNICAÇÕES','RELATÓRIO','RELATÓRIOS',
  'APRESENTAÇÃO','APRESENTAÇÕES','SLIDE','SLIDES','INFOGRÁFICO',
  'STAKEHOLDER','PARTES INTERESSADAS','SPONSOR','PATROCINADOR',
  'RECURSO','RECURSOS','HUMANOS','FINANCEIROS','MATERIAIS','TECNOLÓGICOS',
  'CRONOGRAMA','CRONOGRAMAS','MILESTONE','MARCO','MARCOS',
  'ESCOPO','ENTREGA','SPRINT','ITERAÇÃO','CICLO',

  // ── Saúde e segurança do trabalho ─────────────────────────────
  'SEGURANÇA','SEGURANÇA DO TRABALHO','ACIDENTE','ACIDENTES',
  'RISCO','RISCOS','PERIGO','PERIGOS','HAZARD',
  'EPI','EPC','EQUIPAMENTO DE PROTEÇÃO','PROTEÇÃO INDIVIDUAL','PROTEÇÃO COLETIVA',
  'LUVA','LUVAS','MÁSCARA','MÁSCARAS','ÓCULOS','PROTETOR',
  'JALECO','JALECOS','AVENTAL','AVENTAIS','BOTA','BOTAS',
  'CAPACETE','CAPACETES','CINTO','CINTOS','HARNESS',
  'INCÊNDIO','EXTINTOR','EXTINTORES','BRIGADA','EVACUAÇÃO',
  'PRIMEIROS SOCORROS','PRONTO SOCORRO','HOSPITAL','AED','DESFIBRILADOR',
  'ERGONOMIA','POSTURA','GINÁSTICA LABORAL','LESÃO','AFASTAMENTO',
  'PPRA','PCMSO','LTCAT','PPP','LAUDO','LAUDOS',
  'CIPA','DDS','DIÁLOGO DIÁRIO','PERMISSÃO DE TRABALHO',
  'NR','NORMA REGULAMENTADORA','CLT','PREVIDÊNCIA',
  'BIOSSEGURANÇA','BIOSSEGURIDADE','CONTENÇÃO','NÍVEL DE CONTENÇÃO',
  'DESCARTE BIOLÓGICO','RESÍDUO BIOLÓGICO','AUTOCLAVE','ESTERILIZAÇÃO',
  'FMEA','ANÁLISE DE RISCO','APR','ANÁLISE PRELIMINAR',

  // ── Informática avançada ──────────────────────────────────────
  'COMPUTADOR','COMPUTADORES','DESKTOP','LAPTOP','NOTEBOOK','TABLET',
  'SERVIDOR','SERVIDORES','NUVEM','CLOUD','ARMAZENAMENTO',
  'BANCO DE DADOS','DATABASE','SQL','CONSULTA','QUERY',
  'SOFTWARE','APLICATIVO','APP','SISTEMA','PLATAFORMA',
  'EXCEL','WORD','POWERPOINT','ACCESS','OUTLOOK',
  'INTERNET','INTRANET','EXTRANET','WEB','SITE','PORTAL',
  'EMAIL','E-MAIL','MENSAGEM','CHAT','VIDEOCONFERÊNCIA',
  'SENHA','LOGIN','ACESSO','PERMISSÃO','PERFIL','USUÁRIO',
  'BACKUP','RESTORE','RECUPERAÇÃO','VERSÃO','ATUALIZAÇÃO',
  'SEGURANÇA','ANTIVÍRUS','FIREWALL','CRIPTOGRAFIA','VPN',
  'IMPRESSORA','SCANNER','CÂMERA','PROJETOR','MONITOR','TECLADO','MOUSE',
  'REDE','WIFI','CABO','SWITCH','ROTEADOR','MODEM',
  'PROTOCOLO','IP','HTTP','FTP','SMTP','POP','IMAP',
  'PLANILHA','FÓRMULA','GRÁFICO','TABELA DINÂMICA','FILTRO','MACRO',
  'PDF','DOC','DOCX','XLS','XLSX','PPT','PPTX','JPG','PNG','CSV',
  'UPLOAD','DOWNLOAD','COMPARTILHAR','SINCRONIZAR',

  // ── Números e quantitativos ───────────────────────────────────
  'ZERO','UM','DOIS','TRÊS','QUATRO','CINCO','SEIS','SETE','OITO','NOVE','DEZ',
  'ONZE','DOZE','TREZE','QUATORZE','QUINZE','DEZESSEIS','DEZESSETE','DEZOITO','DEZENOVE','VINTE',
  'TRINTA','QUARENTA','CINQUENTA','SESSENTA','SETENTA','OITENTA','NOVENTA','CEM','CENTo',
  'CENTO','DUZENTOS','TREZENTOS','QUATROCENTOS','QUINHENTOS','SEISCENTOS',
  'SETECENTOS','OITOCENTOS','NOVECENTOS','MIL','MILHÃO','BILHÃO',
  'PRIMEIRO','SEGUNDA','TERCEIRO','QUARTO','QUINTO','SEXTO','SÉTIMO','OITAVO','NONO','DÉCIMO',
  'ÚNICO','DUPLO','TRIPLO','MÚLTIPLO','DOBRO','METADE','TERÇO','QUARTO',
  'MUITO','POUCO','BASTANTE','SUFICIENTE','EXCESSIVO','INSUFICIENTE',
  'MAIS','MENOS','IGUAL','DIFERENTE','MAIOR','MENOR','MÁXIMO','MÍNIMO',
  'TOTAL','SUBTOTAL','PARCIAL','INTEGRAL','COMPLETO','INCOMPLETO',
  'QUANTIDADE','QUALIDADE','FREQUÊNCIA','INTENSIDADE','DURAÇÃO',
  'PERCENTUAL','PROPORÇÃO','RAZÃO','TAXA','ÍNDICE','COEFICIENTE',

  // ── Cores ─────────────────────────────────────────────────────
  'VERDE','VERDES','AMARELO','AMARELA','AMARELOS','AMARELAS',
  'VERMELHO','VERMELHA','VERMELHOS','VERMELHAS',
  'AZUL','AZUIS','BRANCO','BRANCA','BRANCOS','BRANCAS',
  'PRETO','PRETA','PRETOS','PRETAS','CINZA','CINZAS',
  'MARROM','MARRONS','LARANJA','LARANJAS','ROXO','ROXA','ROXOS','ROXAS',
  'ROSA','ROSAS','VIOLETA','LILÁS','BEGE','CREME',
  'TRANSPARENTE','OPACO','OPACA','TURVO','TURVA','LÍMPIDO','LÍMPIDA',

  // ── Adjetivos técnicos ampliados ──────────────────────────────
  'POSITIVO','POSITIVA','NEGATIVO','NEGATIVA','NEUTRO','NEUTRA',
  'ATIVO','ATIVA','ATIVOS','ATIVAS','INATIVO','INATIVA',
  'ESTÁVEL','ESTÁVEIS','INSTÁVEL','INSTÁVEIS','VOLÁTIL','VOLÁTEIS',
  'SOLÚVEL','SOLÚVEIS','INSOLÚVEL','INSOLÚVEIS',
  'TÓXICO','TÓXICA','TÓXICOS','TÓXICAS','ATÓXICO','ATÓXICA',
  'INFLAMÁVEL','INFLAMÁVEIS','CORROSIVO','CORROSIVA',
  'PERIGOSO','PERIGOSA','PERIGOSOS','PERIGOSAS','SEGURO','SEGURA',
  'EFICIENTE','EFICIENTES','EFICAZ','EFICAZES','EFETIVO','EFETIVA',
  'ADEQUADO','ADEQUADA','INADEQUADO','INADEQUADA',
  'DISPONÍVEL','DISPONÍVEIS','INDISPONÍVEL','INDISPONÍVEIS',
  'OBRIGATÓRIO','OBRIGATÓRIA','OPCIONAL','FACULTATIVO','FACULTATIVA',
  'PERMANENTE','PERMANENTES','TEMPORÁRIO','TEMPORÁRIA','PROVISÓRIO','PROVISÓRIA',
  'FORMAL','FORMAIS','INFORMAL','INFORMAIS','OFICIAL','OFICIAIS',
  'PÚBLICO','PÚBLICA','PRIVADO','PRIVADA','CONFIDENCIAL',
  'ORIGINAL','ORIGINAIS','CÓPIA','CÓPIAS','AUTÊNTICO','AUTÊNTICA',
  'VÁLIDO','VÁLIDA','INVÁLIDO','INVÁLIDA','VENCIDO','VENCIDA',
  'NOVO','NOVA','NOVOS','NOVAS','VELHO','VELHA','ANTIGO','ANTIGA',
  'MODERNO','MODERNA','ATUAL','ATUAIS','DESATUALIZADO','DESATUALIZADA',
  'RÁPIDO','RÁPIDA','LENTO','LENTA','ÁGIL','ÁGEIS',
  'SIMPLES','COMPLEXO','COMPLEXA','BÁSICO','BÁSICA','AVANÇADO','AVANÇADA',
  'PADRONIZADO','PADRONIZADA','CUSTOMIZADO','CUSTOMIZADA','PERSONALIZADO','PERSONALIZADA',
  'AUTOMATIZADO','AUTOMATIZADA','MANUAL','MANUAIS',
  'PRESENCIAL','REMOTO','REMOTA','HÍBRIDO','HÍBRIDA','VIRTUAL',

  // ── Preposições e locuções ampliadas ──────────────────────────
  'ATRAVÉS','MEDIANTE','CONFORME','SEGUNDO','PERANTE','ANTE',
  'EXCETO','SALVO','INCLUSIVE','EXCLUSIVE','DESDE','ATÉ',
  'JUNTO','PRÓXIMO','PERTO','LONGE','DISTANTE','DENTRO','FORA',
  'ACIMA','ABAIXO','ATRÁS','FRENTE','LADO','ENTRE','MEIO',
  'DURANTE','ENQUANTO','APÓS','ANTES','QUANDO','SEMPRE','NUNCA',
  'FREQUENTEMENTE','RARAMENTE','EVENTUALMENTE','NORMALMENTE','GERALMENTE',
  'IMEDIATAMENTE','RAPIDAMENTE','GRADUALMENTE','PAULATINAMENTE',
  'ESPECIALMENTE','PRINCIPALMENTE','PARTICULARMENTE','SOBRETUDO',
  'PORTANTO','ASSIM','ENTÃO','CONSEQUENTEMENTE','LOGO',
  'PORÉM','ENTRETANTO','CONTUDO','TODAVIA','NO ENTANTO',
  'ALÉM DISSO','ADEMAIS','OUTROSSIM','TAMBÉM',
  'POR EXEMPLO','OU SEJA','ISTO É','COMO','TAL COMO',
  'DE ACORDO','CONFORME','SEGUNDO','BASEADO','FUNDAMENTADO',
  'EM RELAÇÃO','QUANTO A','NO QUE TANGE','NO TOCANTE',
  'VIA','POR MEIO','POR INTERMÉDIO','ATRAVÉS DE',
]

function levenshtein(a: string, b: string): number {
  const m = a.length, n = b.length
  const dp: number[][] = Array.from({ length: m + 1 }, (_, i) =>
    Array.from({ length: n + 1 }, (_, j) => i === 0 ? j : j === 0 ? i : 0)
  )
  for (let i = 1; i <= m; i++)
    for (let j = 1; j <= n; j++)
      dp[i][j] = a[i-1] === b[j-1]
        ? dp[i-1][j-1]
        : 1 + Math.min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1])
  return dp[m][n]
}

const VOCAB_SET = new Set(VOCABULARIO)

function corrigirPalavra(palavra: string): string {
  if (palavra.length <= 2) return palavra
  if (VOCAB_SET.has(palavra)) return palavra
  const limite = palavra.length <= 5 ? 1 : palavra.length <= 8 ? 2 : 3
  let melhor = palavra, menorDist = Infinity
  for (const ref of VOCABULARIO) {
    if (Math.abs(ref.length - palavra.length) > limite) continue
    const d = levenshtein(palavra, ref)
    if (d < menorDist) { menorDist = d; melhor = ref }
    if (d === 0) break
  }
  return menorDist <= limite ? melhor : palavra
}

function corrigirOrtografia(texto: string): string {
  const upper = texto.toUpperCase()
  return upper.split(/(\s+|[^A-ZÁÉÍÓÚÂÊÎÔÛÃÕÀÈÌÒÙÇ]+)/).map(token => {
    if (/^[A-ZÁÉÍÓÚÂÊÎÔÛÃÕÀÈÌÒÙÇ]+$/.test(token)) return corrigirPalavra(token)
    return token
  }).join('')
}

function normalizar(texto: string): string {
  return corrigirOrtografia(texto.trim())
}

export async function POST() {
  try {
    const auth = await requireManager()
    if (!auth.ok) return auth.response

    const db = createSupabaseServiceClient()

    const { data: activities, error } = await db
      .from('activities')
      .select('id, description')

    if (error) return NextResponse.json({ error: error.message }, { status: 500 })
    if (!activities?.length) return NextResponse.json({ updated: 0, message: 'Nenhuma atividade encontrada.' })

    const toUpdate = activities
      .map(a => ({ id: a.id, original: a.description, corrected: normalizar(a.description) }))
      .filter(a => a.original !== a.corrected)

    if (!toUpdate.length) {
      return NextResponse.json({ updated: 0, message: 'Todas as atividades já estão corretas.' })
    }

    const results = await Promise.all(
      toUpdate.map(({ id, corrected }) =>
        db.from('activities').update({ description: corrected }).eq('id', id)
      )
    )

    const errors = results.filter(r => r.error).map(r => r.error?.message)
    if (errors.length) return NextResponse.json({ error: errors.join(', ') }, { status: 500 })

    return NextResponse.json({
      updated: toUpdate.length,
      corrections: toUpdate.map(a => `"${a.original}" → "${a.corrected}"`),
    })
  } catch (err) {
    console.error('[fix-activities-spelling]', err)
    return NextResponse.json({ error: 'Erro interno.' }, { status: 500 })
  }
}
